package com.acube.pc.domain;

import java.util.Date;

public class ProvFtr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.PROV_FTR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String provFtrCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.SVC_DOMAIN
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String svcDomain;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.NE_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String neId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.IS_USER_DEFINE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String isUserDefine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.IS_BSS_PROV
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String isBssProv;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.MAX_PARAM_CNT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short maxParamCnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.DESCR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String descr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.COMMON_USE_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String commonUseFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.IS_SUSPEND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String isSuspend;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.PROV_NE_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String provNeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.FTR_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Integer ftrPrty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysCreationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String applicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlServiceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short dlUpdateStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_FTR.FTR_KD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String ftrKdCd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.PROV_FTR_CD
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.PROV_FTR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getProvFtrCd() {
		return provFtrCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.PROV_FTR_CD
	 * @param provFtrCd  the value for ABACUS.ABA_PD_PROV_FTR.PROV_FTR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setProvFtrCd(String provFtrCd) {
		this.provFtrCd = provFtrCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.SVC_DOMAIN
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.SVC_DOMAIN
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getSvcDomain() {
		return svcDomain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.SVC_DOMAIN
	 * @param svcDomain  the value for ABACUS.ABA_PD_PROV_FTR.SVC_DOMAIN
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSvcDomain(String svcDomain) {
		this.svcDomain = svcDomain;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.NE_ID
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.NE_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getNeId() {
		return neId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.NE_ID
	 * @param neId  the value for ABACUS.ABA_PD_PROV_FTR.NE_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setNeId(String neId) {
		this.neId = neId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.IS_USER_DEFINE
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.IS_USER_DEFINE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getIsUserDefine() {
		return isUserDefine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.IS_USER_DEFINE
	 * @param isUserDefine  the value for ABACUS.ABA_PD_PROV_FTR.IS_USER_DEFINE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setIsUserDefine(String isUserDefine) {
		this.isUserDefine = isUserDefine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.IS_BSS_PROV
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.IS_BSS_PROV
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getIsBssProv() {
		return isBssProv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.IS_BSS_PROV
	 * @param isBssProv  the value for ABACUS.ABA_PD_PROV_FTR.IS_BSS_PROV
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setIsBssProv(String isBssProv) {
		this.isBssProv = isBssProv;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.MAX_PARAM_CNT
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.MAX_PARAM_CNT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getMaxParamCnt() {
		return maxParamCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.MAX_PARAM_CNT
	 * @param maxParamCnt  the value for ABACUS.ABA_PD_PROV_FTR.MAX_PARAM_CNT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setMaxParamCnt(Short maxParamCnt) {
		this.maxParamCnt = maxParamCnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.DESCR
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.DESCR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDescr() {
		return descr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.DESCR
	 * @param descr  the value for ABACUS.ABA_PD_PROV_FTR.DESCR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDescr(String descr) {
		this.descr = descr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.COMMON_USE_FLAG
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.COMMON_USE_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getCommonUseFlag() {
		return commonUseFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.COMMON_USE_FLAG
	 * @param commonUseFlag  the value for ABACUS.ABA_PD_PROV_FTR.COMMON_USE_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setCommonUseFlag(String commonUseFlag) {
		this.commonUseFlag = commonUseFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.IS_SUSPEND
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.IS_SUSPEND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getIsSuspend() {
		return isSuspend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.IS_SUSPEND
	 * @param isSuspend  the value for ABACUS.ABA_PD_PROV_FTR.IS_SUSPEND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setIsSuspend(String isSuspend) {
		this.isSuspend = isSuspend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.PROV_NE_ID
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.PROV_NE_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getProvNeId() {
		return provNeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.PROV_NE_ID
	 * @param provNeId  the value for ABACUS.ABA_PD_PROV_FTR.PROV_NE_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setProvNeId(String provNeId) {
		this.provNeId = provNeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.FTR_PRTY
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.FTR_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Integer getFtrPrty() {
		return ftrPrty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.FTR_PRTY
	 * @param ftrPrty  the value for ABACUS.ABA_PD_PROV_FTR.FTR_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setFtrPrty(Integer ftrPrty) {
		this.ftrPrty = ftrPrty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.SYS_CREATION_DATE
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysCreationDate() {
		return sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.SYS_CREATION_DATE
	 * @param sysCreationDate  the value for ABACUS.ABA_PD_PROV_FTR.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysCreationDate(Date sysCreationDate) {
		this.sysCreationDate = sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.SYS_UPDATE_DATE
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysUpdateDate() {
		return sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.SYS_UPDATE_DATE
	 * @param sysUpdateDate  the value for ABACUS.ABA_PD_PROV_FTR.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysUpdateDate(Date sysUpdateDate) {
		this.sysUpdateDate = sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.OPERATOR_ID
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.OPERATOR_ID
	 * @param operatorId  the value for ABACUS.ABA_PD_PROV_FTR.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.APPLICATION_ID
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.APPLICATION_ID
	 * @param applicationId  the value for ABACUS.ABA_PD_PROV_FTR.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.DL_SERVICE_CODE
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlServiceCode() {
		return dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.DL_SERVICE_CODE
	 * @param dlServiceCode  the value for ABACUS.ABA_PD_PROV_FTR.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlServiceCode(String dlServiceCode) {
		this.dlServiceCode = dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.DL_UPDATE_STAMP
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getDlUpdateStamp() {
		return dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.DL_UPDATE_STAMP
	 * @param dlUpdateStamp  the value for ABACUS.ABA_PD_PROV_FTR.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlUpdateStamp(Short dlUpdateStamp) {
		this.dlUpdateStamp = dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_FTR.FTR_KD_CD
	 * @return  the value of ABACUS.ABA_PD_PROV_FTR.FTR_KD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getFtrKdCd() {
		return ftrKdCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_FTR.FTR_KD_CD
	 * @param ftrKdCd  the value for ABACUS.ABA_PD_PROV_FTR.FTR_KD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setFtrKdCd(String ftrKdCd) {
		this.ftrKdCd = ftrKdCd;
	}
}