package com.acube.pvs.mapper.mbg;

import com.acube.pvs.domain.PsNeMsgView;
import com.acube.pvs.domain.PsNeMsgViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PsNeMsgViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int countByExample(PsNeMsgViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByExample(PsNeMsgViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByPrimaryKey(@Param("reqDt") String reqDt, @Param("eventCd") String eventCd, @Param("targetNe") String targetNe, @Param("statusCd") String statusCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insert(PsNeMsgView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insertSelective(PsNeMsgView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsNeMsgView> selectByExampleWithRowbounds(PsNeMsgViewExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsNeMsgView> selectByExample(PsNeMsgViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    PsNeMsgView selectByPrimaryKey(@Param("reqDt") String reqDt, @Param("eventCd") String eventCd, @Param("targetNe") String targetNe, @Param("statusCd") String statusCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") PsNeMsgView record, @Param("example") PsNeMsgViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExample(@Param("record") PsNeMsgView record, @Param("example") PsNeMsgViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKeySelective(PsNeMsgView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKey(PsNeMsgView record);
}