package com.acube.pvs.mapper.mbg;

import com.acube.pvs.domain.PsProvParamInfo;
import com.acube.pvs.domain.PsProvParamInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PsProvParamInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int countByExample(PsProvParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByExample(PsProvParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByPrimaryKey(@Param("neId") String neId, @Param("csParamId") String csParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insert(PsProvParamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insertSelective(PsProvParamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsProvParamInfo> selectByExampleWithRowbounds(PsProvParamInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsProvParamInfo> selectByExample(PsProvParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    PsProvParamInfo selectByPrimaryKey(@Param("neId") String neId, @Param("csParamId") String csParamId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") PsProvParamInfo record, @Param("example") PsProvParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExample(@Param("record") PsProvParamInfo record, @Param("example") PsProvParamInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKeySelective(PsProvParamInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_PARAM_INFO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKey(PsProvParamInfo record);
}