package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.ContsSalePrcInfo;
import com.acube.pc.domain.ContsSalePrcInfoExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContsSalePrcInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(ContsSalePrcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(ContsSalePrcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("contsProdCd") String contsProdCd, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(ContsSalePrcInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(ContsSalePrcInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ContsSalePrcInfo> selectByExampleWithRowbounds(ContsSalePrcInfoExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ContsSalePrcInfo> selectByExample(ContsSalePrcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	ContsSalePrcInfo selectByPrimaryKey(@Param("contsProdCd") String contsProdCd, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") ContsSalePrcInfo record, @Param("example") ContsSalePrcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") ContsSalePrcInfo record, @Param("example") ContsSalePrcInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(ContsSalePrcInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_SALE_PRC_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(ContsSalePrcInfo record);
}