package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.DevMdl;
import com.acube.pc.domain.DevMdlExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DevMdlMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(DevMdlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(DevMdlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(String devId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(DevMdl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(DevMdl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DevMdl> selectByExampleWithRowbounds(DevMdlExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DevMdl> selectByExample(DevMdlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	DevMdl selectByPrimaryKey(String devId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") DevMdl record, @Param("example") DevMdlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") DevMdl record, @Param("example") DevMdlExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(DevMdl record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DEV_MDL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(DevMdl record);
}