package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.DiscountForCug;
import com.acube.pc.domain.DiscountForCugExample;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DiscountForCugMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(DiscountForCugExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(DiscountForCugExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("prodCd") String prodCd, @Param("discountRate") BigDecimal discountRate);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(DiscountForCug record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(DiscountForCug record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DiscountForCug> selectByExampleWithRowbounds(DiscountForCugExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DiscountForCug> selectByExample(DiscountForCugExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	DiscountForCug selectByPrimaryKey(@Param("prodCd") String prodCd, @Param("discountRate") BigDecimal discountRate);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") DiscountForCug record, @Param("example") DiscountForCugExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") DiscountForCug record, @Param("example") DiscountForCugExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(DiscountForCug record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DISCOUNT_FOR_CUG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(DiscountForCug record);
}