package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.DscntProdPrty;
import com.acube.pc.domain.DscntProdPrtyExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DscntProdPrtyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(DscntProdPrtyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(DscntProdPrtyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(String prodCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(DscntProdPrty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(DscntProdPrty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DscntProdPrty> selectByExampleWithRowbounds(DscntProdPrtyExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DscntProdPrty> selectByExample(DscntProdPrtyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	DscntProdPrty selectByPrimaryKey(String prodCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") DscntProdPrty record, @Param("example") DscntProdPrtyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") DscntProdPrty record, @Param("example") DscntProdPrtyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(DscntProdPrty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_PRTY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(DscntProdPrty record);
}