package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.DscntProdByGrp;
import com.acube.pc.domain.DscntProdByGrpExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DscntProdByGrpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(DscntProdByGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(DscntProdByGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("dscntGrpId") String dscntGrpId, @Param("prodCd") String prodCd, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(DscntProdByGrp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(DscntProdByGrp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DscntProdByGrp> selectByExampleWithRowbounds(DscntProdByGrpExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DscntProdByGrp> selectByExample(DscntProdByGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	DscntProdByGrp selectByPrimaryKey(@Param("dscntGrpId") String dscntGrpId, @Param("prodCd") String prodCd, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") DscntProdByGrp record, @Param("example") DscntProdByGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") DscntProdByGrp record, @Param("example") DscntProdByGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(DscntProdByGrp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PROD_BY_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(DscntProdByGrp record);
}