package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.FromToProdGrp;
import com.acube.pc.domain.FromToProdGrpExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FromToProdGrpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(FromToProdGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(FromToProdGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("changeSchemeId") String changeSchemeId, @Param("prodGrpId") String prodGrpId, @Param("fromToFlag") String fromToFlag);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(FromToProdGrp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(FromToProdGrp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<FromToProdGrp> selectByExampleWithRowbounds(FromToProdGrpExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<FromToProdGrp> selectByExample(FromToProdGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	FromToProdGrp selectByPrimaryKey(@Param("changeSchemeId") String changeSchemeId, @Param("prodGrpId") String prodGrpId, @Param("fromToFlag") String fromToFlag);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") FromToProdGrp record, @Param("example") FromToProdGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") FromToProdGrp record, @Param("example") FromToProdGrpExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(FromToProdGrp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FROM_TO_PROD_GRP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(FromToProdGrp record);
}