package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.HwConfigByProd;
import com.acube.pc.domain.HwConfigByProdExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface HwConfigByProdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(HwConfigByProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(HwConfigByProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("prodCd") String prodCd, @Param("hwConfigId") String hwConfigId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(HwConfigByProd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(HwConfigByProd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<HwConfigByProd> selectByExampleWithRowbounds(HwConfigByProdExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<HwConfigByProd> selectByExample(HwConfigByProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	HwConfigByProd selectByPrimaryKey(@Param("prodCd") String prodCd, @Param("hwConfigId") String hwConfigId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") HwConfigByProd record, @Param("example") HwConfigByProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") HwConfigByProd record, @Param("example") HwConfigByProdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(HwConfigByProd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_HW_CONFIG_BY_PROD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(HwConfigByProd record);
}