package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.NatnGrpInfo;
import com.acube.pc.domain.NatnGrpInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface NatnGrpInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(NatnGrpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(NatnGrpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(String prodCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(NatnGrpInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(NatnGrpInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<NatnGrpInfo> selectByExampleWithRowbounds(NatnGrpInfoExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<NatnGrpInfo> selectByExample(NatnGrpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	NatnGrpInfo selectByPrimaryKey(String prodCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") NatnGrpInfo record, @Param("example") NatnGrpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") NatnGrpInfo record, @Param("example") NatnGrpInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(NatnGrpInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_GRP_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(NatnGrpInfo record);
}