package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.ProdChangeScheme;
import com.acube.pc.domain.ProdChangeSchemeExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProdChangeSchemeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(ProdChangeSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(ProdChangeSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(String changeSchemeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(ProdChangeScheme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(ProdChangeScheme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ProdChangeScheme> selectByExampleWithRowbounds(ProdChangeSchemeExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ProdChangeScheme> selectByExample(ProdChangeSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	ProdChangeScheme selectByPrimaryKey(String changeSchemeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") ProdChangeScheme record, @Param("example") ProdChangeSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") ProdChangeScheme record, @Param("example") ProdChangeSchemeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(ProdChangeScheme record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(ProdChangeScheme record);
}