package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.ProdChangeTranfSub;
import com.acube.pc.domain.ProdChangeTranfSubExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProdChangeTranfSubMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(ProdChangeTranfSubExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(ProdChangeTranfSubExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("changeSchemeId") String changeSchemeId, @Param("prodCd") String prodCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(ProdChangeTranfSub record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(ProdChangeTranfSub record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ProdChangeTranfSub> selectByExampleWithRowbounds(ProdChangeTranfSubExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ProdChangeTranfSub> selectByExample(ProdChangeTranfSubExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	ProdChangeTranfSub selectByPrimaryKey(@Param("changeSchemeId") String changeSchemeId, @Param("prodCd") String prodCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") ProdChangeTranfSub record, @Param("example") ProdChangeTranfSubExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") ProdChangeTranfSub record, @Param("example") ProdChangeTranfSubExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(ProdChangeTranfSub record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_TRANF_SUB
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(ProdChangeTranfSub record);
}