package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.ProvParamSeq;
import com.acube.pc.domain.ProvParamSeqExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProvParamSeqMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(ProvParamSeqExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(ProvParamSeqExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("provCmd") String provCmd, @Param("provFtrCd") String provFtrCd, @Param("neId") String neId, @Param("pvParamId") String pvParamId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(ProvParamSeq record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(ProvParamSeq record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ProvParamSeq> selectByExampleWithRowbounds(ProvParamSeqExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ProvParamSeq> selectByExample(ProvParamSeqExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	ProvParamSeq selectByPrimaryKey(@Param("provCmd") String provCmd, @Param("provFtrCd") String provFtrCd, @Param("neId") String neId, @Param("pvParamId") String pvParamId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") ProvParamSeq record, @Param("example") ProvParamSeqExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") ProvParamSeq record, @Param("example") ProvParamSeqExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(ProvParamSeq record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_PARAM_SEQ
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(ProvParamSeq record);
}