package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.ProvFtrByDeposit;
import com.acube.pc.domain.ProvFtrByDepositExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProvFtrByDepositMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(ProvFtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(ProvFtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("depositSetId") String depositSetId, @Param("depositId") String depositId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(ProvFtrByDeposit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(ProvFtrByDeposit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ProvFtrByDeposit> selectByExampleWithRowbounds(ProvFtrByDepositExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ProvFtrByDeposit> selectByExample(ProvFtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	ProvFtrByDeposit selectByPrimaryKey(@Param("depositSetId") String depositSetId, @Param("depositId") String depositId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") ProvFtrByDeposit record, @Param("example") ProvFtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") ProvFtrByDeposit record, @Param("example") ProvFtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(ProvFtrByDeposit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROV_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(ProvFtrByDeposit record);
}