package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.Rate;
import com.acube.pc.domain.RateExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(RateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(RateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("inventoryItemId") Long inventoryItemId, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(Rate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(Rate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<Rate> selectByExampleWithRowbounds(RateExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<Rate> selectByExample(RateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	Rate selectByPrimaryKey(@Param("inventoryItemId") Long inventoryItemId, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") Rate record, @Param("example") RateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") Rate record, @Param("example") RateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(Rate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(Rate record);
}