package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.SdrExre;
import com.acube.pc.domain.SdrExreExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SdrExreMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(SdrExreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(SdrExreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("exreDate") Date exreDate, @Param("currency") String currency);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(SdrExre record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(SdrExre record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<SdrExre> selectByExampleWithRowbounds(SdrExreExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<SdrExre> selectByExample(SdrExreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	SdrExre selectByPrimaryKey(@Param("exreDate") Date exreDate, @Param("currency") String currency);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") SdrExre record, @Param("example") SdrExreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") SdrExre record, @Param("example") SdrExreExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(SdrExre record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_SDR_EXRE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(SdrExre record);
}