package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.ThresholdMaster;
import com.acube.pc.domain.ThresholdMasterExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ThresholdMasterMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(ThresholdMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(ThresholdMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(String thresholdId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(ThresholdMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(ThresholdMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ThresholdMaster> selectByExampleWithRowbounds(ThresholdMasterExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ThresholdMaster> selectByExample(ThresholdMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	ThresholdMaster selectByPrimaryKey(String thresholdId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") ThresholdMaster record, @Param("example") ThresholdMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") ThresholdMaster record, @Param("example") ThresholdMasterExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(ThresholdMaster record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_THRESHOLD_MASTER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(ThresholdMaster record);
}