package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.FtrByDeposit;
import com.acube.pc.domain.FtrByDepositExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FtrByDepositMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(FtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(FtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("depositSetId") String depositSetId, @Param("depositId") String depositId, @Param("callType") String callType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(FtrByDeposit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(FtrByDeposit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<FtrByDeposit> selectByExampleWithRowbounds(FtrByDepositExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<FtrByDeposit> selectByExample(FtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	FtrByDeposit selectByPrimaryKey(@Param("depositSetId") String depositSetId, @Param("depositId") String depositId, @Param("callType") String callType);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") FtrByDeposit record, @Param("example") FtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") FtrByDeposit record, @Param("example") FtrByDepositExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(FtrByDeposit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_DEPOSIT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(FtrByDeposit record);
}