package com.acube.pc.domain;

import java.util.Date;

public class ContsForProd {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_PROD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String contsProdCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String contsCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_CONTS_FOR_PROD.IS_APPLY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String isApply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysCreationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_CONTS_FOR_PROD.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_CONTS_FOR_PROD.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String applicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_CONTS_FOR_PROD.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlServiceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_CONTS_FOR_PROD.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short dlUpdateStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_PROD_CD
	 * @return  the value of ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_PROD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getContsProdCd() {
		return contsProdCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_PROD_CD
	 * @param contsProdCd  the value for ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_PROD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setContsProdCd(String contsProdCd) {
		this.contsProdCd = contsProdCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_CD
	 * @return  the value of ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getContsCd() {
		return contsCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_CD
	 * @param contsCd  the value for ABACUS.ABA_PD_CONTS_FOR_PROD.CONTS_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setContsCd(String contsCd) {
		this.contsCd = contsCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.IS_APPLY
	 * @return  the value of ABACUS.ABA_PD_CONTS_FOR_PROD.IS_APPLY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getIsApply() {
		return isApply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.IS_APPLY
	 * @param isApply  the value for ABACUS.ABA_PD_CONTS_FOR_PROD.IS_APPLY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setIsApply(String isApply) {
		this.isApply = isApply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_CREATION_DATE
	 * @return  the value of ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysCreationDate() {
		return sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_CREATION_DATE
	 * @param sysCreationDate  the value for ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysCreationDate(Date sysCreationDate) {
		this.sysCreationDate = sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_UPDATE_DATE
	 * @return  the value of ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysUpdateDate() {
		return sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_UPDATE_DATE
	 * @param sysUpdateDate  the value for ABACUS.ABA_PD_CONTS_FOR_PROD.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysUpdateDate(Date sysUpdateDate) {
		this.sysUpdateDate = sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.OPERATOR_ID
	 * @return  the value of ABACUS.ABA_PD_CONTS_FOR_PROD.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.OPERATOR_ID
	 * @param operatorId  the value for ABACUS.ABA_PD_CONTS_FOR_PROD.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.APPLICATION_ID
	 * @return  the value of ABACUS.ABA_PD_CONTS_FOR_PROD.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.APPLICATION_ID
	 * @param applicationId  the value for ABACUS.ABA_PD_CONTS_FOR_PROD.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.DL_SERVICE_CODE
	 * @return  the value of ABACUS.ABA_PD_CONTS_FOR_PROD.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlServiceCode() {
		return dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.DL_SERVICE_CODE
	 * @param dlServiceCode  the value for ABACUS.ABA_PD_CONTS_FOR_PROD.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlServiceCode(String dlServiceCode) {
		this.dlServiceCode = dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.DL_UPDATE_STAMP
	 * @return  the value of ABACUS.ABA_PD_CONTS_FOR_PROD.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getDlUpdateStamp() {
		return dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_CONTS_FOR_PROD.DL_UPDATE_STAMP
	 * @param dlUpdateStamp  the value for ABACUS.ABA_PD_CONTS_FOR_PROD.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlUpdateStamp(Short dlUpdateStamp) {
		this.dlUpdateStamp = dlUpdateStamp;
	}
}