package com.acube.pc.domain;

import java.util.Date;

public class Ftr {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.FTR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String ftrCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.FTR_KD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String ftrKdCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.FTR_NAME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String ftrName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.UNIT_DV_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String unitDvCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.FTR_KD_DTL_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String ftrKdDtlCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysCreationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String applicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlServiceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_FTR.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short dlUpdateStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.FTR_CD
	 * @return  the value of ABACUS.ABA_PD_FTR.FTR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getFtrCd() {
		return ftrCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.FTR_CD
	 * @param ftrCd  the value for ABACUS.ABA_PD_FTR.FTR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setFtrCd(String ftrCd) {
		this.ftrCd = ftrCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.FTR_KD_CD
	 * @return  the value of ABACUS.ABA_PD_FTR.FTR_KD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getFtrKdCd() {
		return ftrKdCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.FTR_KD_CD
	 * @param ftrKdCd  the value for ABACUS.ABA_PD_FTR.FTR_KD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setFtrKdCd(String ftrKdCd) {
		this.ftrKdCd = ftrKdCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.FTR_NAME
	 * @return  the value of ABACUS.ABA_PD_FTR.FTR_NAME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getFtrName() {
		return ftrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.FTR_NAME
	 * @param ftrName  the value for ABACUS.ABA_PD_FTR.FTR_NAME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setFtrName(String ftrName) {
		this.ftrName = ftrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.UNIT_DV_CD
	 * @return  the value of ABACUS.ABA_PD_FTR.UNIT_DV_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getUnitDvCd() {
		return unitDvCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.UNIT_DV_CD
	 * @param unitDvCd  the value for ABACUS.ABA_PD_FTR.UNIT_DV_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setUnitDvCd(String unitDvCd) {
		this.unitDvCd = unitDvCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.FTR_KD_DTL_CD
	 * @return  the value of ABACUS.ABA_PD_FTR.FTR_KD_DTL_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getFtrKdDtlCd() {
		return ftrKdDtlCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.FTR_KD_DTL_CD
	 * @param ftrKdDtlCd  the value for ABACUS.ABA_PD_FTR.FTR_KD_DTL_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setFtrKdDtlCd(String ftrKdDtlCd) {
		this.ftrKdDtlCd = ftrKdDtlCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.SYS_CREATION_DATE
	 * @return  the value of ABACUS.ABA_PD_FTR.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysCreationDate() {
		return sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.SYS_CREATION_DATE
	 * @param sysCreationDate  the value for ABACUS.ABA_PD_FTR.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysCreationDate(Date sysCreationDate) {
		this.sysCreationDate = sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.SYS_UPDATE_DATE
	 * @return  the value of ABACUS.ABA_PD_FTR.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysUpdateDate() {
		return sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.SYS_UPDATE_DATE
	 * @param sysUpdateDate  the value for ABACUS.ABA_PD_FTR.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysUpdateDate(Date sysUpdateDate) {
		this.sysUpdateDate = sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.OPERATOR_ID
	 * @return  the value of ABACUS.ABA_PD_FTR.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.OPERATOR_ID
	 * @param operatorId  the value for ABACUS.ABA_PD_FTR.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.APPLICATION_ID
	 * @return  the value of ABACUS.ABA_PD_FTR.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.APPLICATION_ID
	 * @param applicationId  the value for ABACUS.ABA_PD_FTR.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.DL_SERVICE_CODE
	 * @return  the value of ABACUS.ABA_PD_FTR.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlServiceCode() {
		return dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.DL_SERVICE_CODE
	 * @param dlServiceCode  the value for ABACUS.ABA_PD_FTR.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlServiceCode(String dlServiceCode) {
		this.dlServiceCode = dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_FTR.DL_UPDATE_STAMP
	 * @return  the value of ABACUS.ABA_PD_FTR.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getDlUpdateStamp() {
		return dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_FTR.DL_UPDATE_STAMP
	 * @param dlUpdateStamp  the value for ABACUS.ABA_PD_FTR.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlUpdateStamp(Short dlUpdateStamp) {
		this.dlUpdateStamp = dlUpdateStamp;
	}
}