package com.acube.pc.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.acube.security.domain.Elements;
import com.acube.security.domain.Role;

public class Member implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.MARKET_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String marketCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.USER_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.SYS_CREATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysCreateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String applicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlServiceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short dlUpdateStamp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.DLR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlrCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.USER_NAME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.PASSWORD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.OLD_PASSWORD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String oldPassword;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.MAX_ADJUST_AMT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Long maxAdjustAmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.EFFECTIVE_DATE8
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String effectiveDate8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.EXPIRATION_DATE8
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String expirationDate8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.EMAIL_ADDRESS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String emailAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.BIRTHDAY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String birthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.AGE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.USER_LEVEL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String userLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.GENDER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.ZIP_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String zipCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.USER_MERRY_YN
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String userMerryYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.HOME_TELNO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String homeTelno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.WORK_TELNO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String workTelno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.MOBILE_TELNO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String mobileTelno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.WORK_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date workDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.USER_STATUS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String userStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.SALE_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String saleFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.CONST_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String constFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.INSTALL_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String installFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.AS_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String asFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.REMOVE_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String removeFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.VILG_ABV_ADDR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String vilgAbvAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.VILG_BLW_ADDR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String vilgBlwAddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.IP_ADDRESS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String ipAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.IP_SCAN_YN
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String ipScanYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.DESCRIPTION
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.STATUS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.USER_NAME2
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String userName2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.USERGROUP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String usergroup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.LOGIN_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String loginId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_OR_USER.ENCODED_PASSWORD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String encodedPassword;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.MARKET_CODE
	 * @return  the value of ABACUS.ABA_OR_USER.MARKET_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getMarketCode() {
		return marketCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.MARKET_CODE
	 * @param marketCode  the value for ABACUS.ABA_OR_USER.MARKET_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setMarketCode(String marketCode) {
		this.marketCode = marketCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.USER_ID
	 * @return  the value of ABACUS.ABA_OR_USER.USER_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.USER_ID
	 * @param userId  the value for ABACUS.ABA_OR_USER.USER_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setUserId(String userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.SYS_CREATE_DATE
	 * @return  the value of ABACUS.ABA_OR_USER.SYS_CREATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysCreateDate() {
		return sysCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.SYS_CREATE_DATE
	 * @param sysCreateDate  the value for ABACUS.ABA_OR_USER.SYS_CREATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysCreateDate(Date sysCreateDate) {
		this.sysCreateDate = sysCreateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.SYS_UPDATE_DATE
	 * @return  the value of ABACUS.ABA_OR_USER.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysUpdateDate() {
		return sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.SYS_UPDATE_DATE
	 * @param sysUpdateDate  the value for ABACUS.ABA_OR_USER.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysUpdateDate(Date sysUpdateDate) {
		this.sysUpdateDate = sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.OPERATOR_ID
	 * @return  the value of ABACUS.ABA_OR_USER.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.OPERATOR_ID
	 * @param operatorId  the value for ABACUS.ABA_OR_USER.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.APPLICATION_ID
	 * @return  the value of ABACUS.ABA_OR_USER.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.APPLICATION_ID
	 * @param applicationId  the value for ABACUS.ABA_OR_USER.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.DL_SERVICE_CODE
	 * @return  the value of ABACUS.ABA_OR_USER.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlServiceCode() {
		return dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.DL_SERVICE_CODE
	 * @param dlServiceCode  the value for ABACUS.ABA_OR_USER.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlServiceCode(String dlServiceCode) {
		this.dlServiceCode = dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.DL_UPDATE_STAMP
	 * @return  the value of ABACUS.ABA_OR_USER.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getDlUpdateStamp() {
		return dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.DL_UPDATE_STAMP
	 * @param dlUpdateStamp  the value for ABACUS.ABA_OR_USER.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlUpdateStamp(Short dlUpdateStamp) {
		this.dlUpdateStamp = dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.DLR_CD
	 * @return  the value of ABACUS.ABA_OR_USER.DLR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlrCd() {
		return dlrCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.DLR_CD
	 * @param dlrCd  the value for ABACUS.ABA_OR_USER.DLR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlrCd(String dlrCd) {
		this.dlrCd = dlrCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.USER_NAME
	 * @return  the value of ABACUS.ABA_OR_USER.USER_NAME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.USER_NAME
	 * @param userName  the value for ABACUS.ABA_OR_USER.USER_NAME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.PASSWORD
	 * @return  the value of ABACUS.ABA_OR_USER.PASSWORD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.PASSWORD
	 * @param password  the value for ABACUS.ABA_OR_USER.PASSWORD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.OLD_PASSWORD
	 * @return  the value of ABACUS.ABA_OR_USER.OLD_PASSWORD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOldPassword() {
		return oldPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.OLD_PASSWORD
	 * @param oldPassword  the value for ABACUS.ABA_OR_USER.OLD_PASSWORD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.MAX_ADJUST_AMT
	 * @return  the value of ABACUS.ABA_OR_USER.MAX_ADJUST_AMT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Long getMaxAdjustAmt() {
		return maxAdjustAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.MAX_ADJUST_AMT
	 * @param maxAdjustAmt  the value for ABACUS.ABA_OR_USER.MAX_ADJUST_AMT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setMaxAdjustAmt(Long maxAdjustAmt) {
		this.maxAdjustAmt = maxAdjustAmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.EFFECTIVE_DATE8
	 * @return  the value of ABACUS.ABA_OR_USER.EFFECTIVE_DATE8
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getEffectiveDate8() {
		return effectiveDate8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.EFFECTIVE_DATE8
	 * @param effectiveDate8  the value for ABACUS.ABA_OR_USER.EFFECTIVE_DATE8
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setEffectiveDate8(String effectiveDate8) {
		this.effectiveDate8 = effectiveDate8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.EXPIRATION_DATE8
	 * @return  the value of ABACUS.ABA_OR_USER.EXPIRATION_DATE8
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getExpirationDate8() {
		return expirationDate8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.EXPIRATION_DATE8
	 * @param expirationDate8  the value for ABACUS.ABA_OR_USER.EXPIRATION_DATE8
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setExpirationDate8(String expirationDate8) {
		this.expirationDate8 = expirationDate8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.EMAIL_ADDRESS
	 * @return  the value of ABACUS.ABA_OR_USER.EMAIL_ADDRESS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getEmailAddress() {
		return emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.EMAIL_ADDRESS
	 * @param emailAddress  the value for ABACUS.ABA_OR_USER.EMAIL_ADDRESS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.BIRTHDAY
	 * @return  the value of ABACUS.ABA_OR_USER.BIRTHDAY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.BIRTHDAY
	 * @param birthday  the value for ABACUS.ABA_OR_USER.BIRTHDAY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.AGE
	 * @return  the value of ABACUS.ABA_OR_USER.AGE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.AGE
	 * @param age  the value for ABACUS.ABA_OR_USER.AGE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setAge(Short age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.USER_LEVEL
	 * @return  the value of ABACUS.ABA_OR_USER.USER_LEVEL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getUserLevel() {
		return userLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.USER_LEVEL
	 * @param userLevel  the value for ABACUS.ABA_OR_USER.USER_LEVEL
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setUserLevel(String userLevel) {
		this.userLevel = userLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.GENDER
	 * @return  the value of ABACUS.ABA_OR_USER.GENDER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.GENDER
	 * @param gender  the value for ABACUS.ABA_OR_USER.GENDER
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.ZIP_CODE
	 * @return  the value of ABACUS.ABA_OR_USER.ZIP_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getZipCode() {
		return zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.ZIP_CODE
	 * @param zipCode  the value for ABACUS.ABA_OR_USER.ZIP_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.USER_MERRY_YN
	 * @return  the value of ABACUS.ABA_OR_USER.USER_MERRY_YN
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getUserMerryYn() {
		return userMerryYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.USER_MERRY_YN
	 * @param userMerryYn  the value for ABACUS.ABA_OR_USER.USER_MERRY_YN
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setUserMerryYn(String userMerryYn) {
		this.userMerryYn = userMerryYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.HOME_TELNO
	 * @return  the value of ABACUS.ABA_OR_USER.HOME_TELNO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getHomeTelno() {
		return homeTelno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.HOME_TELNO
	 * @param homeTelno  the value for ABACUS.ABA_OR_USER.HOME_TELNO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setHomeTelno(String homeTelno) {
		this.homeTelno = homeTelno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.WORK_TELNO
	 * @return  the value of ABACUS.ABA_OR_USER.WORK_TELNO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getWorkTelno() {
		return workTelno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.WORK_TELNO
	 * @param workTelno  the value for ABACUS.ABA_OR_USER.WORK_TELNO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setWorkTelno(String workTelno) {
		this.workTelno = workTelno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.MOBILE_TELNO
	 * @return  the value of ABACUS.ABA_OR_USER.MOBILE_TELNO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getMobileTelno() {
		return mobileTelno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.MOBILE_TELNO
	 * @param mobileTelno  the value for ABACUS.ABA_OR_USER.MOBILE_TELNO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setMobileTelno(String mobileTelno) {
		this.mobileTelno = mobileTelno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.WORK_DATE
	 * @return  the value of ABACUS.ABA_OR_USER.WORK_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getWorkDate() {
		return workDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.WORK_DATE
	 * @param workDate  the value for ABACUS.ABA_OR_USER.WORK_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setWorkDate(Date workDate) {
		this.workDate = workDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.USER_STATUS
	 * @return  the value of ABACUS.ABA_OR_USER.USER_STATUS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.USER_STATUS
	 * @param userStatus  the value for ABACUS.ABA_OR_USER.USER_STATUS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.SALE_FLAG
	 * @return  the value of ABACUS.ABA_OR_USER.SALE_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getSaleFlag() {
		return saleFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.SALE_FLAG
	 * @param saleFlag  the value for ABACUS.ABA_OR_USER.SALE_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSaleFlag(String saleFlag) {
		this.saleFlag = saleFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.CONST_FLAG
	 * @return  the value of ABACUS.ABA_OR_USER.CONST_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getConstFlag() {
		return constFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.CONST_FLAG
	 * @param constFlag  the value for ABACUS.ABA_OR_USER.CONST_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setConstFlag(String constFlag) {
		this.constFlag = constFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.INSTALL_FLAG
	 * @return  the value of ABACUS.ABA_OR_USER.INSTALL_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getInstallFlag() {
		return installFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.INSTALL_FLAG
	 * @param installFlag  the value for ABACUS.ABA_OR_USER.INSTALL_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setInstallFlag(String installFlag) {
		this.installFlag = installFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.AS_FLAG
	 * @return  the value of ABACUS.ABA_OR_USER.AS_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getAsFlag() {
		return asFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.AS_FLAG
	 * @param asFlag  the value for ABACUS.ABA_OR_USER.AS_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setAsFlag(String asFlag) {
		this.asFlag = asFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.REMOVE_FLAG
	 * @return  the value of ABACUS.ABA_OR_USER.REMOVE_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getRemoveFlag() {
		return removeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.REMOVE_FLAG
	 * @param removeFlag  the value for ABACUS.ABA_OR_USER.REMOVE_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setRemoveFlag(String removeFlag) {
		this.removeFlag = removeFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.VILG_ABV_ADDR
	 * @return  the value of ABACUS.ABA_OR_USER.VILG_ABV_ADDR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getVilgAbvAddr() {
		return vilgAbvAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.VILG_ABV_ADDR
	 * @param vilgAbvAddr  the value for ABACUS.ABA_OR_USER.VILG_ABV_ADDR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setVilgAbvAddr(String vilgAbvAddr) {
		this.vilgAbvAddr = vilgAbvAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.VILG_BLW_ADDR
	 * @return  the value of ABACUS.ABA_OR_USER.VILG_BLW_ADDR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getVilgBlwAddr() {
		return vilgBlwAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.VILG_BLW_ADDR
	 * @param vilgBlwAddr  the value for ABACUS.ABA_OR_USER.VILG_BLW_ADDR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setVilgBlwAddr(String vilgBlwAddr) {
		this.vilgBlwAddr = vilgBlwAddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.IP_ADDRESS
	 * @return  the value of ABACUS.ABA_OR_USER.IP_ADDRESS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getIpAddress() {
		return ipAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.IP_ADDRESS
	 * @param ipAddress  the value for ABACUS.ABA_OR_USER.IP_ADDRESS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.IP_SCAN_YN
	 * @return  the value of ABACUS.ABA_OR_USER.IP_SCAN_YN
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getIpScanYn() {
		return ipScanYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.IP_SCAN_YN
	 * @param ipScanYn  the value for ABACUS.ABA_OR_USER.IP_SCAN_YN
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setIpScanYn(String ipScanYn) {
		this.ipScanYn = ipScanYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.DESCRIPTION
	 * @return  the value of ABACUS.ABA_OR_USER.DESCRIPTION
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.DESCRIPTION
	 * @param description  the value for ABACUS.ABA_OR_USER.DESCRIPTION
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.STATUS
	 * @return  the value of ABACUS.ABA_OR_USER.STATUS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.STATUS
	 * @param status  the value for ABACUS.ABA_OR_USER.STATUS
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.USER_NAME2
	 * @return  the value of ABACUS.ABA_OR_USER.USER_NAME2
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getUserName2() {
		return userName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.USER_NAME2
	 * @param userName2  the value for ABACUS.ABA_OR_USER.USER_NAME2
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setUserName2(String userName2) {
		this.userName2 = userName2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.USERGROUP
	 * @return  the value of ABACUS.ABA_OR_USER.USERGROUP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getUsergroup() {
		return usergroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.USERGROUP
	 * @param usergroup  the value for ABACUS.ABA_OR_USER.USERGROUP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setUsergroup(String usergroup) {
		this.usergroup = usergroup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.LOGIN_ID
	 * @return  the value of ABACUS.ABA_OR_USER.LOGIN_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.LOGIN_ID
	 * @param loginId  the value for ABACUS.ABA_OR_USER.LOGIN_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_OR_USER.ENCODED_PASSWORD
	 * @return  the value of ABACUS.ABA_OR_USER.ENCODED_PASSWORD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getEncodedPassword() {
		return encodedPassword;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_OR_USER.ENCODED_PASSWORD
	 * @param encodedPassword  the value for ABACUS.ABA_OR_USER.ENCODED_PASSWORD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setEncodedPassword(String encodedPassword) {
		this.encodedPassword = encodedPassword;
	}

	/*  */
	private static final long serialVersionUID = 8663621250452587916L;
	/****
	 * 추�??�인 ??��??
	 */
	private List<Role> roles ;
	private List<Elements> elements;

	public List<Role> getRoles() {
		return roles;
	}
	
	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	public List<Elements> getElements() {
		return elements;
	}

	public void setElements(List<Elements> elements) {
		this.elements = elements;
	}
	
	
}