package com.acube.pc.domain;

import java.util.Date;

public class NumPrefixByProd {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PROD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String prodCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PREFIX_ALLOWED
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String prefixAllowed;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_STRT_DT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date valdStrtDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_START
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String rangeStart;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RELS_KD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String relsKdCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_END_DT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date valdEndDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_END
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String rangeEnd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysCreationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String applicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlServiceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short dlUpdateStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PROD_CD
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PROD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getProdCd() {
		return prodCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PROD_CD
	 * @param prodCd  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PROD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setProdCd(String prodCd) {
		this.prodCd = prodCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PREFIX_ALLOWED
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PREFIX_ALLOWED
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getPrefixAllowed() {
		return prefixAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PREFIX_ALLOWED
	 * @param prefixAllowed  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.PREFIX_ALLOWED
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setPrefixAllowed(String prefixAllowed) {
		this.prefixAllowed = prefixAllowed;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_STRT_DT
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_STRT_DT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getValdStrtDt() {
		return valdStrtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_STRT_DT
	 * @param valdStrtDt  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_STRT_DT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setValdStrtDt(Date valdStrtDt) {
		this.valdStrtDt = valdStrtDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_START
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_START
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getRangeStart() {
		return rangeStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_START
	 * @param rangeStart  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_START
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setRangeStart(String rangeStart) {
		this.rangeStart = rangeStart;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RELS_KD_CD
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RELS_KD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getRelsKdCd() {
		return relsKdCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RELS_KD_CD
	 * @param relsKdCd  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RELS_KD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setRelsKdCd(String relsKdCd) {
		this.relsKdCd = relsKdCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_END_DT
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_END_DT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getValdEndDt() {
		return valdEndDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_END_DT
	 * @param valdEndDt  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.VALD_END_DT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setValdEndDt(Date valdEndDt) {
		this.valdEndDt = valdEndDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_END
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_END
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getRangeEnd() {
		return rangeEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_END
	 * @param rangeEnd  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.RANGE_END
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setRangeEnd(String rangeEnd) {
		this.rangeEnd = rangeEnd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_CREATION_DATE
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysCreationDate() {
		return sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_CREATION_DATE
	 * @param sysCreationDate  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysCreationDate(Date sysCreationDate) {
		this.sysCreationDate = sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_UPDATE_DATE
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysUpdateDate() {
		return sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_UPDATE_DATE
	 * @param sysUpdateDate  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysUpdateDate(Date sysUpdateDate) {
		this.sysUpdateDate = sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.OPERATOR_ID
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.OPERATOR_ID
	 * @param operatorId  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.APPLICATION_ID
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.APPLICATION_ID
	 * @param applicationId  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_SERVICE_CODE
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlServiceCode() {
		return dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_SERVICE_CODE
	 * @param dlServiceCode  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlServiceCode(String dlServiceCode) {
		this.dlServiceCode = dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_UPDATE_STAMP
	 * @return  the value of ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getDlUpdateStamp() {
		return dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_UPDATE_STAMP
	 * @param dlUpdateStamp  the value for ABACUS.ABA_PD_NUM_PREFIX_BY_PROD.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlUpdateStamp(Short dlUpdateStamp) {
		this.dlUpdateStamp = dlUpdateStamp;
	}
}