package com.acube.pc.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProdChangeSchemeExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public ProdChangeSchemeExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andChangeSchemeIdIsNull() {
			addCriterion("CHANGE_SCHEME_ID is null");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdIsNotNull() {
			addCriterion("CHANGE_SCHEME_ID is not null");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdEqualTo(String value) {
			addCriterion("CHANGE_SCHEME_ID =", value, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdNotEqualTo(String value) {
			addCriterion("CHANGE_SCHEME_ID <>", value, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdGreaterThan(String value) {
			addCriterion("CHANGE_SCHEME_ID >", value, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdGreaterThanOrEqualTo(String value) {
			addCriterion("CHANGE_SCHEME_ID >=", value, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdLessThan(String value) {
			addCriterion("CHANGE_SCHEME_ID <", value, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdLessThanOrEqualTo(String value) {
			addCriterion("CHANGE_SCHEME_ID <=", value, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdLike(String value) {
			addCriterion("CHANGE_SCHEME_ID like", value, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdNotLike(String value) {
			addCriterion("CHANGE_SCHEME_ID not like", value, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdIn(List<String> values) {
			addCriterion("CHANGE_SCHEME_ID in", values, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdNotIn(List<String> values) {
			addCriterion("CHANGE_SCHEME_ID not in", values, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdBetween(String value1, String value2) {
			addCriterion("CHANGE_SCHEME_ID between", value1, value2, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeIdNotBetween(String value1, String value2) {
			addCriterion("CHANGE_SCHEME_ID not between", value1, value2, "changeSchemeId");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameIsNull() {
			addCriterion("CHANGE_SCHEME_NAME is null");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameIsNotNull() {
			addCriterion("CHANGE_SCHEME_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameEqualTo(String value) {
			addCriterion("CHANGE_SCHEME_NAME =", value, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameNotEqualTo(String value) {
			addCriterion("CHANGE_SCHEME_NAME <>", value, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameGreaterThan(String value) {
			addCriterion("CHANGE_SCHEME_NAME >", value, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameGreaterThanOrEqualTo(String value) {
			addCriterion("CHANGE_SCHEME_NAME >=", value, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameLessThan(String value) {
			addCriterion("CHANGE_SCHEME_NAME <", value, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameLessThanOrEqualTo(String value) {
			addCriterion("CHANGE_SCHEME_NAME <=", value, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameLike(String value) {
			addCriterion("CHANGE_SCHEME_NAME like", value, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameNotLike(String value) {
			addCriterion("CHANGE_SCHEME_NAME not like", value, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameIn(List<String> values) {
			addCriterion("CHANGE_SCHEME_NAME in", values, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameNotIn(List<String> values) {
			addCriterion("CHANGE_SCHEME_NAME not in", values, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameBetween(String value1, String value2) {
			addCriterion("CHANGE_SCHEME_NAME between", value1, value2, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andChangeSchemeNameNotBetween(String value1, String value2) {
			addCriterion("CHANGE_SCHEME_NAME not between", value1, value2, "changeSchemeName");
			return (Criteria) this;
		}

		public Criteria andSvcDomainIsNull() {
			addCriterion("SVC_DOMAIN is null");
			return (Criteria) this;
		}

		public Criteria andSvcDomainIsNotNull() {
			addCriterion("SVC_DOMAIN is not null");
			return (Criteria) this;
		}

		public Criteria andSvcDomainEqualTo(String value) {
			addCriterion("SVC_DOMAIN =", value, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainNotEqualTo(String value) {
			addCriterion("SVC_DOMAIN <>", value, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainGreaterThan(String value) {
			addCriterion("SVC_DOMAIN >", value, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainGreaterThanOrEqualTo(String value) {
			addCriterion("SVC_DOMAIN >=", value, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainLessThan(String value) {
			addCriterion("SVC_DOMAIN <", value, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainLessThanOrEqualTo(String value) {
			addCriterion("SVC_DOMAIN <=", value, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainLike(String value) {
			addCriterion("SVC_DOMAIN like", value, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainNotLike(String value) {
			addCriterion("SVC_DOMAIN not like", value, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainIn(List<String> values) {
			addCriterion("SVC_DOMAIN in", values, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainNotIn(List<String> values) {
			addCriterion("SVC_DOMAIN not in", values, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainBetween(String value1, String value2) {
			addCriterion("SVC_DOMAIN between", value1, value2, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andSvcDomainNotBetween(String value1, String value2) {
			addCriterion("SVC_DOMAIN not between", value1, value2, "svcDomain");
			return (Criteria) this;
		}

		public Criteria andBillTypeIsNull() {
			addCriterion("BILL_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andBillTypeIsNotNull() {
			addCriterion("BILL_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andBillTypeEqualTo(String value) {
			addCriterion("BILL_TYPE =", value, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeNotEqualTo(String value) {
			addCriterion("BILL_TYPE <>", value, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeGreaterThan(String value) {
			addCriterion("BILL_TYPE >", value, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeGreaterThanOrEqualTo(String value) {
			addCriterion("BILL_TYPE >=", value, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeLessThan(String value) {
			addCriterion("BILL_TYPE <", value, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeLessThanOrEqualTo(String value) {
			addCriterion("BILL_TYPE <=", value, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeLike(String value) {
			addCriterion("BILL_TYPE like", value, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeNotLike(String value) {
			addCriterion("BILL_TYPE not like", value, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeIn(List<String> values) {
			addCriterion("BILL_TYPE in", values, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeNotIn(List<String> values) {
			addCriterion("BILL_TYPE not in", values, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeBetween(String value1, String value2) {
			addCriterion("BILL_TYPE between", value1, value2, "billType");
			return (Criteria) this;
		}

		public Criteria andBillTypeNotBetween(String value1, String value2) {
			addCriterion("BILL_TYPE not between", value1, value2, "billType");
			return (Criteria) this;
		}

		public Criteria andChangeFeeIsNull() {
			addCriterion("CHANGE_FEE is null");
			return (Criteria) this;
		}

		public Criteria andChangeFeeIsNotNull() {
			addCriterion("CHANGE_FEE is not null");
			return (Criteria) this;
		}

		public Criteria andChangeFeeEqualTo(BigDecimal value) {
			addCriterion("CHANGE_FEE =", value, "changeFee");
			return (Criteria) this;
		}

		public Criteria andChangeFeeNotEqualTo(BigDecimal value) {
			addCriterion("CHANGE_FEE <>", value, "changeFee");
			return (Criteria) this;
		}

		public Criteria andChangeFeeGreaterThan(BigDecimal value) {
			addCriterion("CHANGE_FEE >", value, "changeFee");
			return (Criteria) this;
		}

		public Criteria andChangeFeeGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("CHANGE_FEE >=", value, "changeFee");
			return (Criteria) this;
		}

		public Criteria andChangeFeeLessThan(BigDecimal value) {
			addCriterion("CHANGE_FEE <", value, "changeFee");
			return (Criteria) this;
		}

		public Criteria andChangeFeeLessThanOrEqualTo(BigDecimal value) {
			addCriterion("CHANGE_FEE <=", value, "changeFee");
			return (Criteria) this;
		}

		public Criteria andChangeFeeIn(List<BigDecimal> values) {
			addCriterion("CHANGE_FEE in", values, "changeFee");
			return (Criteria) this;
		}

		public Criteria andChangeFeeNotIn(List<BigDecimal> values) {
			addCriterion("CHANGE_FEE not in", values, "changeFee");
			return (Criteria) this;
		}

		public Criteria andChangeFeeBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CHANGE_FEE between", value1, value2, "changeFee");
			return (Criteria) this;
		}

		public Criteria andChangeFeeNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("CHANGE_FEE not between", value1, value2, "changeFee");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeIsNull() {
			addCriterion("FIRST_CHANGE_FEE_FREE is null");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeIsNotNull() {
			addCriterion("FIRST_CHANGE_FEE_FREE is not null");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeEqualTo(String value) {
			addCriterion("FIRST_CHANGE_FEE_FREE =", value, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeNotEqualTo(String value) {
			addCriterion("FIRST_CHANGE_FEE_FREE <>", value, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeGreaterThan(String value) {
			addCriterion("FIRST_CHANGE_FEE_FREE >", value, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeGreaterThanOrEqualTo(String value) {
			addCriterion("FIRST_CHANGE_FEE_FREE >=", value, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeLessThan(String value) {
			addCriterion("FIRST_CHANGE_FEE_FREE <", value, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeLessThanOrEqualTo(String value) {
			addCriterion("FIRST_CHANGE_FEE_FREE <=", value, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeLike(String value) {
			addCriterion("FIRST_CHANGE_FEE_FREE like", value, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeNotLike(String value) {
			addCriterion("FIRST_CHANGE_FEE_FREE not like", value, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeIn(List<String> values) {
			addCriterion("FIRST_CHANGE_FEE_FREE in", values, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeNotIn(List<String> values) {
			addCriterion("FIRST_CHANGE_FEE_FREE not in", values, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeBetween(String value1, String value2) {
			addCriterion("FIRST_CHANGE_FEE_FREE between", value1, value2, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andFirstChangeFeeFreeNotBetween(String value1, String value2) {
			addCriterion("FIRST_CHANGE_FEE_FREE not between", value1, value2, "firstChangeFeeFree");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsIsNull() {
			addCriterion("ACTIVE_OPTIONS is null");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsIsNotNull() {
			addCriterion("ACTIVE_OPTIONS is not null");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsEqualTo(String value) {
			addCriterion("ACTIVE_OPTIONS =", value, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsNotEqualTo(String value) {
			addCriterion("ACTIVE_OPTIONS <>", value, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsGreaterThan(String value) {
			addCriterion("ACTIVE_OPTIONS >", value, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsGreaterThanOrEqualTo(String value) {
			addCriterion("ACTIVE_OPTIONS >=", value, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsLessThan(String value) {
			addCriterion("ACTIVE_OPTIONS <", value, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsLessThanOrEqualTo(String value) {
			addCriterion("ACTIVE_OPTIONS <=", value, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsLike(String value) {
			addCriterion("ACTIVE_OPTIONS like", value, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsNotLike(String value) {
			addCriterion("ACTIVE_OPTIONS not like", value, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsIn(List<String> values) {
			addCriterion("ACTIVE_OPTIONS in", values, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsNotIn(List<String> values) {
			addCriterion("ACTIVE_OPTIONS not in", values, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsBetween(String value1, String value2) {
			addCriterion("ACTIVE_OPTIONS between", value1, value2, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveOptionsNotBetween(String value1, String value2) {
			addCriterion("ACTIVE_OPTIONS not between", value1, value2, "activeOptions");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysIsNull() {
			addCriterion("ACTIVE_NDAYS is null");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysIsNotNull() {
			addCriterion("ACTIVE_NDAYS is not null");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysEqualTo(Long value) {
			addCriterion("ACTIVE_NDAYS =", value, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysNotEqualTo(Long value) {
			addCriterion("ACTIVE_NDAYS <>", value, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysGreaterThan(Long value) {
			addCriterion("ACTIVE_NDAYS >", value, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysGreaterThanOrEqualTo(Long value) {
			addCriterion("ACTIVE_NDAYS >=", value, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysLessThan(Long value) {
			addCriterion("ACTIVE_NDAYS <", value, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysLessThanOrEqualTo(Long value) {
			addCriterion("ACTIVE_NDAYS <=", value, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysIn(List<Long> values) {
			addCriterion("ACTIVE_NDAYS in", values, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysNotIn(List<Long> values) {
			addCriterion("ACTIVE_NDAYS not in", values, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysBetween(Long value1, Long value2) {
			addCriterion("ACTIVE_NDAYS between", value1, value2, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveNdaysNotBetween(Long value1, Long value2) {
			addCriterion("ACTIVE_NDAYS not between", value1, value2, "activeNdays");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateIsNull() {
			addCriterion("ACTIVE_FIXED_DATE is null");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateIsNotNull() {
			addCriterion("ACTIVE_FIXED_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateEqualTo(Date value) {
			addCriterion("ACTIVE_FIXED_DATE =", value, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateNotEqualTo(Date value) {
			addCriterion("ACTIVE_FIXED_DATE <>", value, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateGreaterThan(Date value) {
			addCriterion("ACTIVE_FIXED_DATE >", value, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("ACTIVE_FIXED_DATE >=", value, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateLessThan(Date value) {
			addCriterion("ACTIVE_FIXED_DATE <", value, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateLessThanOrEqualTo(Date value) {
			addCriterion("ACTIVE_FIXED_DATE <=", value, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateIn(List<Date> values) {
			addCriterion("ACTIVE_FIXED_DATE in", values, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateNotIn(List<Date> values) {
			addCriterion("ACTIVE_FIXED_DATE not in", values, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateBetween(Date value1, Date value2) {
			addCriterion("ACTIVE_FIXED_DATE between", value1, value2, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andActiveFixedDateNotBetween(Date value1, Date value2) {
			addCriterion("ACTIVE_FIXED_DATE not between", value1, value2, "activeFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsIsNull() {
			addCriterion("GRACE_OPTIONS is null");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsIsNotNull() {
			addCriterion("GRACE_OPTIONS is not null");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsEqualTo(String value) {
			addCriterion("GRACE_OPTIONS =", value, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsNotEqualTo(String value) {
			addCriterion("GRACE_OPTIONS <>", value, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsGreaterThan(String value) {
			addCriterion("GRACE_OPTIONS >", value, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsGreaterThanOrEqualTo(String value) {
			addCriterion("GRACE_OPTIONS >=", value, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsLessThan(String value) {
			addCriterion("GRACE_OPTIONS <", value, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsLessThanOrEqualTo(String value) {
			addCriterion("GRACE_OPTIONS <=", value, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsLike(String value) {
			addCriterion("GRACE_OPTIONS like", value, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsNotLike(String value) {
			addCriterion("GRACE_OPTIONS not like", value, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsIn(List<String> values) {
			addCriterion("GRACE_OPTIONS in", values, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsNotIn(List<String> values) {
			addCriterion("GRACE_OPTIONS not in", values, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsBetween(String value1, String value2) {
			addCriterion("GRACE_OPTIONS between", value1, value2, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceOptionsNotBetween(String value1, String value2) {
			addCriterion("GRACE_OPTIONS not between", value1, value2, "graceOptions");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysIsNull() {
			addCriterion("GRACE_NDAYS is null");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysIsNotNull() {
			addCriterion("GRACE_NDAYS is not null");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysEqualTo(Long value) {
			addCriterion("GRACE_NDAYS =", value, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysNotEqualTo(Long value) {
			addCriterion("GRACE_NDAYS <>", value, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysGreaterThan(Long value) {
			addCriterion("GRACE_NDAYS >", value, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysGreaterThanOrEqualTo(Long value) {
			addCriterion("GRACE_NDAYS >=", value, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysLessThan(Long value) {
			addCriterion("GRACE_NDAYS <", value, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysLessThanOrEqualTo(Long value) {
			addCriterion("GRACE_NDAYS <=", value, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysIn(List<Long> values) {
			addCriterion("GRACE_NDAYS in", values, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysNotIn(List<Long> values) {
			addCriterion("GRACE_NDAYS not in", values, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysBetween(Long value1, Long value2) {
			addCriterion("GRACE_NDAYS between", value1, value2, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceNdaysNotBetween(Long value1, Long value2) {
			addCriterion("GRACE_NDAYS not between", value1, value2, "graceNdays");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateIsNull() {
			addCriterion("GRACE_FIXED_DATE is null");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateIsNotNull() {
			addCriterion("GRACE_FIXED_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateEqualTo(Date value) {
			addCriterion("GRACE_FIXED_DATE =", value, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateNotEqualTo(Date value) {
			addCriterion("GRACE_FIXED_DATE <>", value, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateGreaterThan(Date value) {
			addCriterion("GRACE_FIXED_DATE >", value, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateGreaterThanOrEqualTo(Date value) {
			addCriterion("GRACE_FIXED_DATE >=", value, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateLessThan(Date value) {
			addCriterion("GRACE_FIXED_DATE <", value, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateLessThanOrEqualTo(Date value) {
			addCriterion("GRACE_FIXED_DATE <=", value, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateIn(List<Date> values) {
			addCriterion("GRACE_FIXED_DATE in", values, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateNotIn(List<Date> values) {
			addCriterion("GRACE_FIXED_DATE not in", values, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateBetween(Date value1, Date value2) {
			addCriterion("GRACE_FIXED_DATE between", value1, value2, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andGraceFixedDateNotBetween(Date value1, Date value2) {
			addCriterion("GRACE_FIXED_DATE not between", value1, value2, "graceFixedDate");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndIsNull() {
			addCriterion("CHECK_ALLOWED_PREFIX_IND is null");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndIsNotNull() {
			addCriterion("CHECK_ALLOWED_PREFIX_IND is not null");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndEqualTo(String value) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND =", value, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndNotEqualTo(String value) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND <>", value, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndGreaterThan(String value) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND >", value, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndGreaterThanOrEqualTo(String value) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND >=", value, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndLessThan(String value) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND <", value, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndLessThanOrEqualTo(String value) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND <=", value, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndLike(String value) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND like", value, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndNotLike(String value) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND not like", value, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndIn(List<String> values) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND in", values, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndNotIn(List<String> values) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND not in", values, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndBetween(String value1, String value2) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND between", value1, value2, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andCheckAllowedPrefixIndNotBetween(String value1, String value2) {
			addCriterion("CHECK_ALLOWED_PREFIX_IND not between", value1, value2, "checkAllowedPrefixInd");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateIsNull() {
			addCriterion("SYS_CREATION_DATE is null");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateIsNotNull() {
			addCriterion("SYS_CREATION_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateEqualTo(Date value) {
			addCriterion("SYS_CREATION_DATE =", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateNotEqualTo(Date value) {
			addCriterion("SYS_CREATION_DATE <>", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateGreaterThan(Date value) {
			addCriterion("SYS_CREATION_DATE >", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateGreaterThanOrEqualTo(Date value) {
			addCriterion("SYS_CREATION_DATE >=", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateLessThan(Date value) {
			addCriterion("SYS_CREATION_DATE <", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateLessThanOrEqualTo(Date value) {
			addCriterion("SYS_CREATION_DATE <=", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateIn(List<Date> values) {
			addCriterion("SYS_CREATION_DATE in", values, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateNotIn(List<Date> values) {
			addCriterion("SYS_CREATION_DATE not in", values, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateBetween(Date value1, Date value2) {
			addCriterion("SYS_CREATION_DATE between", value1, value2, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateNotBetween(Date value1, Date value2) {
			addCriterion("SYS_CREATION_DATE not between", value1, value2, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateIsNull() {
			addCriterion("SYS_UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateIsNotNull() {
			addCriterion("SYS_UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateEqualTo(Date value) {
			addCriterion("SYS_UPDATE_DATE =", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateNotEqualTo(Date value) {
			addCriterion("SYS_UPDATE_DATE <>", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateGreaterThan(Date value) {
			addCriterion("SYS_UPDATE_DATE >", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("SYS_UPDATE_DATE >=", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateLessThan(Date value) {
			addCriterion("SYS_UPDATE_DATE <", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("SYS_UPDATE_DATE <=", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateIn(List<Date> values) {
			addCriterion("SYS_UPDATE_DATE in", values, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateNotIn(List<Date> values) {
			addCriterion("SYS_UPDATE_DATE not in", values, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateBetween(Date value1, Date value2) {
			addCriterion("SYS_UPDATE_DATE between", value1, value2, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("SYS_UPDATE_DATE not between", value1, value2, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andOperatorIdIsNull() {
			addCriterion("OPERATOR_ID is null");
			return (Criteria) this;
		}

		public Criteria andOperatorIdIsNotNull() {
			addCriterion("OPERATOR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOperatorIdEqualTo(String value) {
			addCriterion("OPERATOR_ID =", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdNotEqualTo(String value) {
			addCriterion("OPERATOR_ID <>", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdGreaterThan(String value) {
			addCriterion("OPERATOR_ID >", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR_ID >=", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdLessThan(String value) {
			addCriterion("OPERATOR_ID <", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdLessThanOrEqualTo(String value) {
			addCriterion("OPERATOR_ID <=", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdLike(String value) {
			addCriterion("OPERATOR_ID like", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdNotLike(String value) {
			addCriterion("OPERATOR_ID not like", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdIn(List<String> values) {
			addCriterion("OPERATOR_ID in", values, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdNotIn(List<String> values) {
			addCriterion("OPERATOR_ID not in", values, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdBetween(String value1, String value2) {
			addCriterion("OPERATOR_ID between", value1, value2, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdNotBetween(String value1, String value2) {
			addCriterion("OPERATOR_ID not between", value1, value2, "operatorId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdIsNull() {
			addCriterion("APPLICATION_ID is null");
			return (Criteria) this;
		}

		public Criteria andApplicationIdIsNotNull() {
			addCriterion("APPLICATION_ID is not null");
			return (Criteria) this;
		}

		public Criteria andApplicationIdEqualTo(String value) {
			addCriterion("APPLICATION_ID =", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotEqualTo(String value) {
			addCriterion("APPLICATION_ID <>", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdGreaterThan(String value) {
			addCriterion("APPLICATION_ID >", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdGreaterThanOrEqualTo(String value) {
			addCriterion("APPLICATION_ID >=", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdLessThan(String value) {
			addCriterion("APPLICATION_ID <", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdLessThanOrEqualTo(String value) {
			addCriterion("APPLICATION_ID <=", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdLike(String value) {
			addCriterion("APPLICATION_ID like", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotLike(String value) {
			addCriterion("APPLICATION_ID not like", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdIn(List<String> values) {
			addCriterion("APPLICATION_ID in", values, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotIn(List<String> values) {
			addCriterion("APPLICATION_ID not in", values, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdBetween(String value1, String value2) {
			addCriterion("APPLICATION_ID between", value1, value2, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotBetween(String value1, String value2) {
			addCriterion("APPLICATION_ID not between", value1, value2, "applicationId");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeIsNull() {
			addCriterion("DL_SERVICE_CODE is null");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeIsNotNull() {
			addCriterion("DL_SERVICE_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeEqualTo(String value) {
			addCriterion("DL_SERVICE_CODE =", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeNotEqualTo(String value) {
			addCriterion("DL_SERVICE_CODE <>", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeGreaterThan(String value) {
			addCriterion("DL_SERVICE_CODE >", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeGreaterThanOrEqualTo(String value) {
			addCriterion("DL_SERVICE_CODE >=", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeLessThan(String value) {
			addCriterion("DL_SERVICE_CODE <", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeLessThanOrEqualTo(String value) {
			addCriterion("DL_SERVICE_CODE <=", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeLike(String value) {
			addCriterion("DL_SERVICE_CODE like", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeNotLike(String value) {
			addCriterion("DL_SERVICE_CODE not like", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeIn(List<String> values) {
			addCriterion("DL_SERVICE_CODE in", values, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeNotIn(List<String> values) {
			addCriterion("DL_SERVICE_CODE not in", values, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeBetween(String value1, String value2) {
			addCriterion("DL_SERVICE_CODE between", value1, value2, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeNotBetween(String value1, String value2) {
			addCriterion("DL_SERVICE_CODE not between", value1, value2, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampIsNull() {
			addCriterion("DL_UPDATE_STAMP is null");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampIsNotNull() {
			addCriterion("DL_UPDATE_STAMP is not null");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampEqualTo(Short value) {
			addCriterion("DL_UPDATE_STAMP =", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampNotEqualTo(Short value) {
			addCriterion("DL_UPDATE_STAMP <>", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampGreaterThan(Short value) {
			addCriterion("DL_UPDATE_STAMP >", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampGreaterThanOrEqualTo(Short value) {
			addCriterion("DL_UPDATE_STAMP >=", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampLessThan(Short value) {
			addCriterion("DL_UPDATE_STAMP <", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampLessThanOrEqualTo(Short value) {
			addCriterion("DL_UPDATE_STAMP <=", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampIn(List<Short> values) {
			addCriterion("DL_UPDATE_STAMP in", values, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampNotIn(List<Short> values) {
			addCriterion("DL_UPDATE_STAMP not in", values, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampBetween(Short value1, Short value2) {
			addCriterion("DL_UPDATE_STAMP between", value1, value2, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampNotBetween(Short value1, Short value2) {
			addCriterion("DL_UPDATE_STAMP not between", value1, value2, "dlUpdateStamp");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ABACUS.ABA_PD_PROD_CHANGE_SCHEME
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 20 14:06:41 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}