package com.acube.pc.domain;

import java.util.Date;

public class ProdChngTranfCounter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.CHANGE_SCHEME_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String changeSchemeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.COUNTER_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String counterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysCreationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String applicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlServiceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short dlUpdateStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.CHANGE_SCHEME_ID
	 * @return  the value of ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.CHANGE_SCHEME_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getChangeSchemeId() {
		return changeSchemeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.CHANGE_SCHEME_ID
	 * @param changeSchemeId  the value for ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.CHANGE_SCHEME_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setChangeSchemeId(String changeSchemeId) {
		this.changeSchemeId = changeSchemeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.COUNTER_ID
	 * @return  the value of ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.COUNTER_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getCounterId() {
		return counterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.COUNTER_ID
	 * @param counterId  the value for ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.COUNTER_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setCounterId(String counterId) {
		this.counterId = counterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_CREATION_DATE
	 * @return  the value of ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysCreationDate() {
		return sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_CREATION_DATE
	 * @param sysCreationDate  the value for ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysCreationDate(Date sysCreationDate) {
		this.sysCreationDate = sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_UPDATE_DATE
	 * @return  the value of ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysUpdateDate() {
		return sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_UPDATE_DATE
	 * @param sysUpdateDate  the value for ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysUpdateDate(Date sysUpdateDate) {
		this.sysUpdateDate = sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.OPERATOR_ID
	 * @return  the value of ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.OPERATOR_ID
	 * @param operatorId  the value for ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.APPLICATION_ID
	 * @return  the value of ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.APPLICATION_ID
	 * @param applicationId  the value for ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_SERVICE_CODE
	 * @return  the value of ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlServiceCode() {
		return dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_SERVICE_CODE
	 * @param dlServiceCode  the value for ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlServiceCode(String dlServiceCode) {
		this.dlServiceCode = dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_UPDATE_STAMP
	 * @return  the value of ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getDlUpdateStamp() {
		return dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_UPDATE_STAMP
	 * @param dlUpdateStamp  the value for ABACUS.ABA_PD_PROD_CHNG_TRANF_COUNTER.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlUpdateStamp(Short dlUpdateStamp) {
		this.dlUpdateStamp = dlUpdateStamp;
	}
}