package com.acube.pc.domain;

import java.util.ArrayList;
import java.util.List;

public class ProdDepositCondExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public ProdDepositCondExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andProdCdIsNull() {
			addCriterion("PROD_CD is null");
			return (Criteria) this;
		}

		public Criteria andProdCdIsNotNull() {
			addCriterion("PROD_CD is not null");
			return (Criteria) this;
		}

		public Criteria andProdCdEqualTo(String value) {
			addCriterion("PROD_CD =", value, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdNotEqualTo(String value) {
			addCriterion("PROD_CD <>", value, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdGreaterThan(String value) {
			addCriterion("PROD_CD >", value, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdGreaterThanOrEqualTo(String value) {
			addCriterion("PROD_CD >=", value, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdLessThan(String value) {
			addCriterion("PROD_CD <", value, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdLessThanOrEqualTo(String value) {
			addCriterion("PROD_CD <=", value, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdLike(String value) {
			addCriterion("PROD_CD like", value, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdNotLike(String value) {
			addCriterion("PROD_CD not like", value, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdIn(List<String> values) {
			addCriterion("PROD_CD in", values, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdNotIn(List<String> values) {
			addCriterion("PROD_CD not in", values, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdBetween(String value1, String value2) {
			addCriterion("PROD_CD between", value1, value2, "prodCd");
			return (Criteria) this;
		}

		public Criteria andProdCdNotBetween(String value1, String value2) {
			addCriterion("PROD_CD not between", value1, value2, "prodCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdIsNull() {
			addCriterion("TRGT_MAIN_PROD_CD is null");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdIsNotNull() {
			addCriterion("TRGT_MAIN_PROD_CD is not null");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdEqualTo(String value) {
			addCriterion("TRGT_MAIN_PROD_CD =", value, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdNotEqualTo(String value) {
			addCriterion("TRGT_MAIN_PROD_CD <>", value, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdGreaterThan(String value) {
			addCriterion("TRGT_MAIN_PROD_CD >", value, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdGreaterThanOrEqualTo(String value) {
			addCriterion("TRGT_MAIN_PROD_CD >=", value, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdLessThan(String value) {
			addCriterion("TRGT_MAIN_PROD_CD <", value, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdLessThanOrEqualTo(String value) {
			addCriterion("TRGT_MAIN_PROD_CD <=", value, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdLike(String value) {
			addCriterion("TRGT_MAIN_PROD_CD like", value, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdNotLike(String value) {
			addCriterion("TRGT_MAIN_PROD_CD not like", value, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdIn(List<String> values) {
			addCriterion("TRGT_MAIN_PROD_CD in", values, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdNotIn(List<String> values) {
			addCriterion("TRGT_MAIN_PROD_CD not in", values, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdBetween(String value1, String value2) {
			addCriterion("TRGT_MAIN_PROD_CD between", value1, value2, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andTrgtMainProdCdNotBetween(String value1, String value2) {
			addCriterion("TRGT_MAIN_PROD_CD not between", value1, value2, "trgtMainProdCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdIsNull() {
			addCriterion("FTR_CD is null");
			return (Criteria) this;
		}

		public Criteria andFtrCdIsNotNull() {
			addCriterion("FTR_CD is not null");
			return (Criteria) this;
		}

		public Criteria andFtrCdEqualTo(String value) {
			addCriterion("FTR_CD =", value, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdNotEqualTo(String value) {
			addCriterion("FTR_CD <>", value, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdGreaterThan(String value) {
			addCriterion("FTR_CD >", value, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdGreaterThanOrEqualTo(String value) {
			addCriterion("FTR_CD >=", value, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdLessThan(String value) {
			addCriterion("FTR_CD <", value, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdLessThanOrEqualTo(String value) {
			addCriterion("FTR_CD <=", value, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdLike(String value) {
			addCriterion("FTR_CD like", value, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdNotLike(String value) {
			addCriterion("FTR_CD not like", value, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdIn(List<String> values) {
			addCriterion("FTR_CD in", values, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdNotIn(List<String> values) {
			addCriterion("FTR_CD not in", values, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdBetween(String value1, String value2) {
			addCriterion("FTR_CD between", value1, value2, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andFtrCdNotBetween(String value1, String value2) {
			addCriterion("FTR_CD not between", value1, value2, "ftrCd");
			return (Criteria) this;
		}

		public Criteria andMinDepositIsNull() {
			addCriterion("MIN_DEPOSIT is null");
			return (Criteria) this;
		}

		public Criteria andMinDepositIsNotNull() {
			addCriterion("MIN_DEPOSIT is not null");
			return (Criteria) this;
		}

		public Criteria andMinDepositEqualTo(Long value) {
			addCriterion("MIN_DEPOSIT =", value, "minDeposit");
			return (Criteria) this;
		}

		public Criteria andMinDepositNotEqualTo(Long value) {
			addCriterion("MIN_DEPOSIT <>", value, "minDeposit");
			return (Criteria) this;
		}

		public Criteria andMinDepositGreaterThan(Long value) {
			addCriterion("MIN_DEPOSIT >", value, "minDeposit");
			return (Criteria) this;
		}

		public Criteria andMinDepositGreaterThanOrEqualTo(Long value) {
			addCriterion("MIN_DEPOSIT >=", value, "minDeposit");
			return (Criteria) this;
		}

		public Criteria andMinDepositLessThan(Long value) {
			addCriterion("MIN_DEPOSIT <", value, "minDeposit");
			return (Criteria) this;
		}

		public Criteria andMinDepositLessThanOrEqualTo(Long value) {
			addCriterion("MIN_DEPOSIT <=", value, "minDeposit");
			return (Criteria) this;
		}

		public Criteria andMinDepositIn(List<Long> values) {
			addCriterion("MIN_DEPOSIT in", values, "minDeposit");
			return (Criteria) this;
		}

		public Criteria andMinDepositNotIn(List<Long> values) {
			addCriterion("MIN_DEPOSIT not in", values, "minDeposit");
			return (Criteria) this;
		}

		public Criteria andMinDepositBetween(Long value1, Long value2) {
			addCriterion("MIN_DEPOSIT between", value1, value2, "minDeposit");
			return (Criteria) this;
		}

		public Criteria andMinDepositNotBetween(Long value1, Long value2) {
			addCriterion("MIN_DEPOSIT not between", value1, value2, "minDeposit");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ABACUS.ABA_PD_PROD_DEPOSIT_COND
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 20 14:06:41 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}