package com.acube.pc.domain;

import java.util.Date;

public class ProvParamSeq {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_CMD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String provCmd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_FTR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String provFtrCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.NE_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String neId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PV_PARAM_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String pvParamId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.USER_DEF_VALUE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String userDefValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PARAM_SEQ_NO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short paramSeqNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.MANDATORY_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String mandatoryFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysCreationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String applicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlServiceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short dlUpdateStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_CMD
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_CMD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getProvCmd() {
		return provCmd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_CMD
	 * @param provCmd  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_CMD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setProvCmd(String provCmd) {
		this.provCmd = provCmd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_FTR_CD
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_FTR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getProvFtrCd() {
		return provFtrCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_FTR_CD
	 * @param provFtrCd  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.PROV_FTR_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setProvFtrCd(String provFtrCd) {
		this.provFtrCd = provFtrCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.NE_ID
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.NE_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getNeId() {
		return neId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.NE_ID
	 * @param neId  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.NE_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setNeId(String neId) {
		this.neId = neId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PV_PARAM_ID
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.PV_PARAM_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getPvParamId() {
		return pvParamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PV_PARAM_ID
	 * @param pvParamId  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.PV_PARAM_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setPvParamId(String pvParamId) {
		this.pvParamId = pvParamId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.USER_DEF_VALUE
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.USER_DEF_VALUE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getUserDefValue() {
		return userDefValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.USER_DEF_VALUE
	 * @param userDefValue  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.USER_DEF_VALUE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setUserDefValue(String userDefValue) {
		this.userDefValue = userDefValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PARAM_SEQ_NO
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.PARAM_SEQ_NO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getParamSeqNo() {
		return paramSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.PARAM_SEQ_NO
	 * @param paramSeqNo  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.PARAM_SEQ_NO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setParamSeqNo(Short paramSeqNo) {
		this.paramSeqNo = paramSeqNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.MANDATORY_FLAG
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.MANDATORY_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getMandatoryFlag() {
		return mandatoryFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.MANDATORY_FLAG
	 * @param mandatoryFlag  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.MANDATORY_FLAG
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setMandatoryFlag(String mandatoryFlag) {
		this.mandatoryFlag = mandatoryFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_CREATION_DATE
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysCreationDate() {
		return sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_CREATION_DATE
	 * @param sysCreationDate  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysCreationDate(Date sysCreationDate) {
		this.sysCreationDate = sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_UPDATE_DATE
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysUpdateDate() {
		return sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_UPDATE_DATE
	 * @param sysUpdateDate  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysUpdateDate(Date sysUpdateDate) {
		this.sysUpdateDate = sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.OPERATOR_ID
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.OPERATOR_ID
	 * @param operatorId  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.APPLICATION_ID
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.APPLICATION_ID
	 * @param applicationId  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_SERVICE_CODE
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlServiceCode() {
		return dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_SERVICE_CODE
	 * @param dlServiceCode  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlServiceCode(String dlServiceCode) {
		this.dlServiceCode = dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_UPDATE_STAMP
	 * @return  the value of ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getDlUpdateStamp() {
		return dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_UPDATE_STAMP
	 * @param dlUpdateStamp  the value for ABACUS.ABA_PD_PROV_PARAM_SEQ.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlUpdateStamp(Short dlUpdateStamp) {
		this.dlUpdateStamp = dlUpdateStamp;
	}
}