package com.acube.pc.domain;

import java.util.Date;

public class SpclNoInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.PROD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String prodCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String prefix;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.PARTNER_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String partnerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.CALL_TYPE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String callType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.SPCL_NO_TYPE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String spclNoType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX_NAME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String prefixName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysCreationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String applicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlServiceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_SPCL_NO_INFO.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short dlUpdateStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.PROD_CD
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.PROD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getProdCd() {
		return prodCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.PROD_CD
	 * @param prodCd  the value for ABACUS.ABA_PD_SPCL_NO_INFO.PROD_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setProdCd(String prodCd) {
		this.prodCd = prodCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getPrefix() {
		return prefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX
	 * @param prefix  the value for ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.PARTNER_ID
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.PARTNER_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getPartnerId() {
		return partnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.PARTNER_ID
	 * @param partnerId  the value for ABACUS.ABA_PD_SPCL_NO_INFO.PARTNER_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setPartnerId(String partnerId) {
		this.partnerId = partnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.CALL_TYPE
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.CALL_TYPE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getCallType() {
		return callType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.CALL_TYPE
	 * @param callType  the value for ABACUS.ABA_PD_SPCL_NO_INFO.CALL_TYPE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setCallType(String callType) {
		this.callType = callType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.SPCL_NO_TYPE
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.SPCL_NO_TYPE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getSpclNoType() {
		return spclNoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.SPCL_NO_TYPE
	 * @param spclNoType  the value for ABACUS.ABA_PD_SPCL_NO_INFO.SPCL_NO_TYPE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSpclNoType(String spclNoType) {
		this.spclNoType = spclNoType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX_NAME
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX_NAME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getPrefixName() {
		return prefixName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX_NAME
	 * @param prefixName  the value for ABACUS.ABA_PD_SPCL_NO_INFO.PREFIX_NAME
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setPrefixName(String prefixName) {
		this.prefixName = prefixName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.SYS_CREATION_DATE
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysCreationDate() {
		return sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.SYS_CREATION_DATE
	 * @param sysCreationDate  the value for ABACUS.ABA_PD_SPCL_NO_INFO.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysCreationDate(Date sysCreationDate) {
		this.sysCreationDate = sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.SYS_UPDATE_DATE
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysUpdateDate() {
		return sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.SYS_UPDATE_DATE
	 * @param sysUpdateDate  the value for ABACUS.ABA_PD_SPCL_NO_INFO.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysUpdateDate(Date sysUpdateDate) {
		this.sysUpdateDate = sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.OPERATOR_ID
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.OPERATOR_ID
	 * @param operatorId  the value for ABACUS.ABA_PD_SPCL_NO_INFO.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.APPLICATION_ID
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.APPLICATION_ID
	 * @param applicationId  the value for ABACUS.ABA_PD_SPCL_NO_INFO.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.DL_SERVICE_CODE
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlServiceCode() {
		return dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.DL_SERVICE_CODE
	 * @param dlServiceCode  the value for ABACUS.ABA_PD_SPCL_NO_INFO.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlServiceCode(String dlServiceCode) {
		this.dlServiceCode = dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.DL_UPDATE_STAMP
	 * @return  the value of ABACUS.ABA_PD_SPCL_NO_INFO.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getDlUpdateStamp() {
		return dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_SPCL_NO_INFO.DL_UPDATE_STAMP
	 * @param dlUpdateStamp  the value for ABACUS.ABA_PD_SPCL_NO_INFO.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlUpdateStamp(Short dlUpdateStamp) {
		this.dlUpdateStamp = dlUpdateStamp;
	}
}