package com.acube.pc.domain;

import java.util.Date;

public class TmSetCd {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_TM_SET_CD.TIME_BAND_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String timeBandCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_TM_SET_CD.RATE_INTERVAL_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String rateIntervalCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_TM_SET_CD.DSCR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dscr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_TM_SET_CD.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysCreationDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_TM_SET_CD.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Date sysUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_TM_SET_CD.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String operatorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_TM_SET_CD.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String applicationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_TM_SET_CD.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private String dlServiceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ABACUS.ABA_PD_TM_SET_CD.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	private Short dlUpdateStamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_TM_SET_CD.TIME_BAND_CD
	 * @return  the value of ABACUS.ABA_PD_TM_SET_CD.TIME_BAND_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getTimeBandCd() {
		return timeBandCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_TM_SET_CD.TIME_BAND_CD
	 * @param timeBandCd  the value for ABACUS.ABA_PD_TM_SET_CD.TIME_BAND_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setTimeBandCd(String timeBandCd) {
		this.timeBandCd = timeBandCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_TM_SET_CD.RATE_INTERVAL_CD
	 * @return  the value of ABACUS.ABA_PD_TM_SET_CD.RATE_INTERVAL_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getRateIntervalCd() {
		return rateIntervalCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_TM_SET_CD.RATE_INTERVAL_CD
	 * @param rateIntervalCd  the value for ABACUS.ABA_PD_TM_SET_CD.RATE_INTERVAL_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setRateIntervalCd(String rateIntervalCd) {
		this.rateIntervalCd = rateIntervalCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_TM_SET_CD.DSCR
	 * @return  the value of ABACUS.ABA_PD_TM_SET_CD.DSCR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDscr() {
		return dscr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_TM_SET_CD.DSCR
	 * @param dscr  the value for ABACUS.ABA_PD_TM_SET_CD.DSCR
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDscr(String dscr) {
		this.dscr = dscr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_TM_SET_CD.SYS_CREATION_DATE
	 * @return  the value of ABACUS.ABA_PD_TM_SET_CD.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysCreationDate() {
		return sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_TM_SET_CD.SYS_CREATION_DATE
	 * @param sysCreationDate  the value for ABACUS.ABA_PD_TM_SET_CD.SYS_CREATION_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysCreationDate(Date sysCreationDate) {
		this.sysCreationDate = sysCreationDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_TM_SET_CD.SYS_UPDATE_DATE
	 * @return  the value of ABACUS.ABA_PD_TM_SET_CD.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Date getSysUpdateDate() {
		return sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_TM_SET_CD.SYS_UPDATE_DATE
	 * @param sysUpdateDate  the value for ABACUS.ABA_PD_TM_SET_CD.SYS_UPDATE_DATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setSysUpdateDate(Date sysUpdateDate) {
		this.sysUpdateDate = sysUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_TM_SET_CD.OPERATOR_ID
	 * @return  the value of ABACUS.ABA_PD_TM_SET_CD.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOperatorId() {
		return operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_TM_SET_CD.OPERATOR_ID
	 * @param operatorId  the value for ABACUS.ABA_PD_TM_SET_CD.OPERATOR_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOperatorId(String operatorId) {
		this.operatorId = operatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_TM_SET_CD.APPLICATION_ID
	 * @return  the value of ABACUS.ABA_PD_TM_SET_CD.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getApplicationId() {
		return applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_TM_SET_CD.APPLICATION_ID
	 * @param applicationId  the value for ABACUS.ABA_PD_TM_SET_CD.APPLICATION_ID
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setApplicationId(String applicationId) {
		this.applicationId = applicationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_TM_SET_CD.DL_SERVICE_CODE
	 * @return  the value of ABACUS.ABA_PD_TM_SET_CD.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getDlServiceCode() {
		return dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_TM_SET_CD.DL_SERVICE_CODE
	 * @param dlServiceCode  the value for ABACUS.ABA_PD_TM_SET_CD.DL_SERVICE_CODE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlServiceCode(String dlServiceCode) {
		this.dlServiceCode = dlServiceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ABACUS.ABA_PD_TM_SET_CD.DL_UPDATE_STAMP
	 * @return  the value of ABACUS.ABA_PD_TM_SET_CD.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Short getDlUpdateStamp() {
		return dlUpdateStamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ABACUS.ABA_PD_TM_SET_CD.DL_UPDATE_STAMP
	 * @param dlUpdateStamp  the value for ABACUS.ABA_PD_TM_SET_CD.DL_UPDATE_STAMP
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDlUpdateStamp(Short dlUpdateStamp) {
		this.dlUpdateStamp = dlUpdateStamp;
	}
}