package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.PrefixSettlement;
import com.acube.pc.domain.PrefixSettlementExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PrefixSettlementMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(PrefixSettlementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(PrefixSettlementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("partnerId") String partnerId, @Param("strtPrefix") String strtPrefix, @Param("endPrefix") String endPrefix, @Param("serviceDate") Date serviceDate);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(PrefixSettlement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(PrefixSettlement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<PrefixSettlement> selectByExampleWithRowbounds(PrefixSettlementExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<PrefixSettlement> selectByExample(PrefixSettlementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	PrefixSettlement selectByPrimaryKey(@Param("partnerId") String partnerId, @Param("strtPrefix") String strtPrefix, @Param("endPrefix") String endPrefix, @Param("serviceDate") Date serviceDate);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") PrefixSettlement record, @Param("example") PrefixSettlementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") PrefixSettlement record, @Param("example") PrefixSettlementExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(PrefixSettlement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_PREFIX_SETTLEMENT
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(PrefixSettlement record);
}