package com.acube.pvs.mapper.mbg;

import com.acube.pvs.domain.PsUiAlarmConf;
import com.acube.pvs.domain.PsUiAlarmConfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import com.acube.pvs.domain.PsUiAlarmConfKey;

public interface PsUiAlarmConfMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	int countByExample(PsUiAlarmConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	int deleteByExample(PsUiAlarmConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	int deleteByPrimaryKey(PsUiAlarmConfKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	int insert(PsUiAlarmConf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	int insertSelective(PsUiAlarmConf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	List<PsUiAlarmConf> selectByExampleWithRowbounds(PsUiAlarmConfExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	List<PsUiAlarmConf> selectByExample(PsUiAlarmConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	PsUiAlarmConf selectByPrimaryKey(PsUiAlarmConfKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	int updateByExampleSelective(@Param("record") PsUiAlarmConf record, @Param("example") PsUiAlarmConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	int updateByExample(@Param("record") PsUiAlarmConf record, @Param("example") PsUiAlarmConfExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	int updateByPrimaryKeySelective(PsUiAlarmConf record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PMSADM.ABA_PS_UI_ALARM_CONF
	 * @mbggenerated  Fri Dec 12 11:34:09 KST 2014
	 */
	int updateByPrimaryKey(PsUiAlarmConf record);
}