package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.LifecycleStatesInfo;
import com.acube.pc.domain.LifecycleStatesInfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface LifecycleStatesInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(LifecycleStatesInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(LifecycleStatesInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("lifeCycleId") String lifeCycleId, @Param("states") String states);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(LifecycleStatesInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(LifecycleStatesInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<LifecycleStatesInfo> selectByExampleWithRowbounds(LifecycleStatesInfoExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<LifecycleStatesInfo> selectByExample(LifecycleStatesInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	LifecycleStatesInfo selectByPrimaryKey(@Param("lifeCycleId") String lifeCycleId, @Param("states") String states);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") LifecycleStatesInfo record, @Param("example") LifecycleStatesInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") LifecycleStatesInfo record, @Param("example") LifecycleStatesInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(LifecycleStatesInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_LIFECYCLE_STATES_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(LifecycleStatesInfo record);
}