package com.acube.pc.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NatnInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public NatnInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCountryCdIsNull() {
			addCriterion("COUNTRY_CD is null");
			return (Criteria) this;
		}

		public Criteria andCountryCdIsNotNull() {
			addCriterion("COUNTRY_CD is not null");
			return (Criteria) this;
		}

		public Criteria andCountryCdEqualTo(String value) {
			addCriterion("COUNTRY_CD =", value, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdNotEqualTo(String value) {
			addCriterion("COUNTRY_CD <>", value, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdGreaterThan(String value) {
			addCriterion("COUNTRY_CD >", value, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdGreaterThanOrEqualTo(String value) {
			addCriterion("COUNTRY_CD >=", value, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdLessThan(String value) {
			addCriterion("COUNTRY_CD <", value, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdLessThanOrEqualTo(String value) {
			addCriterion("COUNTRY_CD <=", value, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdLike(String value) {
			addCriterion("COUNTRY_CD like", value, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdNotLike(String value) {
			addCriterion("COUNTRY_CD not like", value, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdIn(List<String> values) {
			addCriterion("COUNTRY_CD in", values, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdNotIn(List<String> values) {
			addCriterion("COUNTRY_CD not in", values, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdBetween(String value1, String value2) {
			addCriterion("COUNTRY_CD between", value1, value2, "countryCd");
			return (Criteria) this;
		}

		public Criteria andCountryCdNotBetween(String value1, String value2) {
			addCriterion("COUNTRY_CD not between", value1, value2, "countryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdIsNull() {
			addCriterion("ISO_COUNTRY_CD is null");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdIsNotNull() {
			addCriterion("ISO_COUNTRY_CD is not null");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdEqualTo(String value) {
			addCriterion("ISO_COUNTRY_CD =", value, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdNotEqualTo(String value) {
			addCriterion("ISO_COUNTRY_CD <>", value, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdGreaterThan(String value) {
			addCriterion("ISO_COUNTRY_CD >", value, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdGreaterThanOrEqualTo(String value) {
			addCriterion("ISO_COUNTRY_CD >=", value, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdLessThan(String value) {
			addCriterion("ISO_COUNTRY_CD <", value, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdLessThanOrEqualTo(String value) {
			addCriterion("ISO_COUNTRY_CD <=", value, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdLike(String value) {
			addCriterion("ISO_COUNTRY_CD like", value, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdNotLike(String value) {
			addCriterion("ISO_COUNTRY_CD not like", value, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdIn(List<String> values) {
			addCriterion("ISO_COUNTRY_CD in", values, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdNotIn(List<String> values) {
			addCriterion("ISO_COUNTRY_CD not in", values, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdBetween(String value1, String value2) {
			addCriterion("ISO_COUNTRY_CD between", value1, value2, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andIsoCountryCdNotBetween(String value1, String value2) {
			addCriterion("ISO_COUNTRY_CD not between", value1, value2, "isoCountryCd");
			return (Criteria) this;
		}

		public Criteria andCountryNameIsNull() {
			addCriterion("COUNTRY_NAME is null");
			return (Criteria) this;
		}

		public Criteria andCountryNameIsNotNull() {
			addCriterion("COUNTRY_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andCountryNameEqualTo(String value) {
			addCriterion("COUNTRY_NAME =", value, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameNotEqualTo(String value) {
			addCriterion("COUNTRY_NAME <>", value, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameGreaterThan(String value) {
			addCriterion("COUNTRY_NAME >", value, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameGreaterThanOrEqualTo(String value) {
			addCriterion("COUNTRY_NAME >=", value, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameLessThan(String value) {
			addCriterion("COUNTRY_NAME <", value, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameLessThanOrEqualTo(String value) {
			addCriterion("COUNTRY_NAME <=", value, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameLike(String value) {
			addCriterion("COUNTRY_NAME like", value, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameNotLike(String value) {
			addCriterion("COUNTRY_NAME not like", value, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameIn(List<String> values) {
			addCriterion("COUNTRY_NAME in", values, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameNotIn(List<String> values) {
			addCriterion("COUNTRY_NAME not in", values, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameBetween(String value1, String value2) {
			addCriterion("COUNTRY_NAME between", value1, value2, "countryName");
			return (Criteria) this;
		}

		public Criteria andCountryNameNotBetween(String value1, String value2) {
			addCriterion("COUNTRY_NAME not between", value1, value2, "countryName");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixIsNull() {
			addCriterion("INTL_PREFIX is null");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixIsNotNull() {
			addCriterion("INTL_PREFIX is not null");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixEqualTo(String value) {
			addCriterion("INTL_PREFIX =", value, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixNotEqualTo(String value) {
			addCriterion("INTL_PREFIX <>", value, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixGreaterThan(String value) {
			addCriterion("INTL_PREFIX >", value, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixGreaterThanOrEqualTo(String value) {
			addCriterion("INTL_PREFIX >=", value, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixLessThan(String value) {
			addCriterion("INTL_PREFIX <", value, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixLessThanOrEqualTo(String value) {
			addCriterion("INTL_PREFIX <=", value, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixLike(String value) {
			addCriterion("INTL_PREFIX like", value, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixNotLike(String value) {
			addCriterion("INTL_PREFIX not like", value, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixIn(List<String> values) {
			addCriterion("INTL_PREFIX in", values, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixNotIn(List<String> values) {
			addCriterion("INTL_PREFIX not in", values, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixBetween(String value1, String value2) {
			addCriterion("INTL_PREFIX between", value1, value2, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andIntlPrefixNotBetween(String value1, String value2) {
			addCriterion("INTL_PREFIX not between", value1, value2, "intlPrefix");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetIsNull() {
			addCriterion("GMT_OFFSET is null");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetIsNotNull() {
			addCriterion("GMT_OFFSET is not null");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetEqualTo(BigDecimal value) {
			addCriterion("GMT_OFFSET =", value, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetNotEqualTo(BigDecimal value) {
			addCriterion("GMT_OFFSET <>", value, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetGreaterThan(BigDecimal value) {
			addCriterion("GMT_OFFSET >", value, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("GMT_OFFSET >=", value, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetLessThan(BigDecimal value) {
			addCriterion("GMT_OFFSET <", value, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetLessThanOrEqualTo(BigDecimal value) {
			addCriterion("GMT_OFFSET <=", value, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetIn(List<BigDecimal> values) {
			addCriterion("GMT_OFFSET in", values, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetNotIn(List<BigDecimal> values) {
			addCriterion("GMT_OFFSET not in", values, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("GMT_OFFSET between", value1, value2, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andGmtOffsetNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("GMT_OFFSET not between", value1, value2, "gmtOffset");
			return (Criteria) this;
		}

		public Criteria andCurrencyIsNull() {
			addCriterion("CURRENCY is null");
			return (Criteria) this;
		}

		public Criteria andCurrencyIsNotNull() {
			addCriterion("CURRENCY is not null");
			return (Criteria) this;
		}

		public Criteria andCurrencyEqualTo(String value) {
			addCriterion("CURRENCY =", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotEqualTo(String value) {
			addCriterion("CURRENCY <>", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyGreaterThan(String value) {
			addCriterion("CURRENCY >", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
			addCriterion("CURRENCY >=", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyLessThan(String value) {
			addCriterion("CURRENCY <", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyLessThanOrEqualTo(String value) {
			addCriterion("CURRENCY <=", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyLike(String value) {
			addCriterion("CURRENCY like", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotLike(String value) {
			addCriterion("CURRENCY not like", value, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyIn(List<String> values) {
			addCriterion("CURRENCY in", values, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotIn(List<String> values) {
			addCriterion("CURRENCY not in", values, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyBetween(String value1, String value2) {
			addCriterion("CURRENCY between", value1, value2, "currency");
			return (Criteria) this;
		}

		public Criteria andCurrencyNotBetween(String value1, String value2) {
			addCriterion("CURRENCY not between", value1, value2, "currency");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateIsNull() {
			addCriterion("SYS_CREATION_DATE is null");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateIsNotNull() {
			addCriterion("SYS_CREATION_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateEqualTo(Date value) {
			addCriterion("SYS_CREATION_DATE =", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateNotEqualTo(Date value) {
			addCriterion("SYS_CREATION_DATE <>", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateGreaterThan(Date value) {
			addCriterion("SYS_CREATION_DATE >", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateGreaterThanOrEqualTo(Date value) {
			addCriterion("SYS_CREATION_DATE >=", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateLessThan(Date value) {
			addCriterion("SYS_CREATION_DATE <", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateLessThanOrEqualTo(Date value) {
			addCriterion("SYS_CREATION_DATE <=", value, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateIn(List<Date> values) {
			addCriterion("SYS_CREATION_DATE in", values, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateNotIn(List<Date> values) {
			addCriterion("SYS_CREATION_DATE not in", values, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateBetween(Date value1, Date value2) {
			addCriterion("SYS_CREATION_DATE between", value1, value2, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysCreationDateNotBetween(Date value1, Date value2) {
			addCriterion("SYS_CREATION_DATE not between", value1, value2, "sysCreationDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateIsNull() {
			addCriterion("SYS_UPDATE_DATE is null");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateIsNotNull() {
			addCriterion("SYS_UPDATE_DATE is not null");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateEqualTo(Date value) {
			addCriterion("SYS_UPDATE_DATE =", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateNotEqualTo(Date value) {
			addCriterion("SYS_UPDATE_DATE <>", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateGreaterThan(Date value) {
			addCriterion("SYS_UPDATE_DATE >", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("SYS_UPDATE_DATE >=", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateLessThan(Date value) {
			addCriterion("SYS_UPDATE_DATE <", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("SYS_UPDATE_DATE <=", value, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateIn(List<Date> values) {
			addCriterion("SYS_UPDATE_DATE in", values, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateNotIn(List<Date> values) {
			addCriterion("SYS_UPDATE_DATE not in", values, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateBetween(Date value1, Date value2) {
			addCriterion("SYS_UPDATE_DATE between", value1, value2, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andSysUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("SYS_UPDATE_DATE not between", value1, value2, "sysUpdateDate");
			return (Criteria) this;
		}

		public Criteria andOperatorIdIsNull() {
			addCriterion("OPERATOR_ID is null");
			return (Criteria) this;
		}

		public Criteria andOperatorIdIsNotNull() {
			addCriterion("OPERATOR_ID is not null");
			return (Criteria) this;
		}

		public Criteria andOperatorIdEqualTo(String value) {
			addCriterion("OPERATOR_ID =", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdNotEqualTo(String value) {
			addCriterion("OPERATOR_ID <>", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdGreaterThan(String value) {
			addCriterion("OPERATOR_ID >", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR_ID >=", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdLessThan(String value) {
			addCriterion("OPERATOR_ID <", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdLessThanOrEqualTo(String value) {
			addCriterion("OPERATOR_ID <=", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdLike(String value) {
			addCriterion("OPERATOR_ID like", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdNotLike(String value) {
			addCriterion("OPERATOR_ID not like", value, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdIn(List<String> values) {
			addCriterion("OPERATOR_ID in", values, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdNotIn(List<String> values) {
			addCriterion("OPERATOR_ID not in", values, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdBetween(String value1, String value2) {
			addCriterion("OPERATOR_ID between", value1, value2, "operatorId");
			return (Criteria) this;
		}

		public Criteria andOperatorIdNotBetween(String value1, String value2) {
			addCriterion("OPERATOR_ID not between", value1, value2, "operatorId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdIsNull() {
			addCriterion("APPLICATION_ID is null");
			return (Criteria) this;
		}

		public Criteria andApplicationIdIsNotNull() {
			addCriterion("APPLICATION_ID is not null");
			return (Criteria) this;
		}

		public Criteria andApplicationIdEqualTo(String value) {
			addCriterion("APPLICATION_ID =", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotEqualTo(String value) {
			addCriterion("APPLICATION_ID <>", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdGreaterThan(String value) {
			addCriterion("APPLICATION_ID >", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdGreaterThanOrEqualTo(String value) {
			addCriterion("APPLICATION_ID >=", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdLessThan(String value) {
			addCriterion("APPLICATION_ID <", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdLessThanOrEqualTo(String value) {
			addCriterion("APPLICATION_ID <=", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdLike(String value) {
			addCriterion("APPLICATION_ID like", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotLike(String value) {
			addCriterion("APPLICATION_ID not like", value, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdIn(List<String> values) {
			addCriterion("APPLICATION_ID in", values, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotIn(List<String> values) {
			addCriterion("APPLICATION_ID not in", values, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdBetween(String value1, String value2) {
			addCriterion("APPLICATION_ID between", value1, value2, "applicationId");
			return (Criteria) this;
		}

		public Criteria andApplicationIdNotBetween(String value1, String value2) {
			addCriterion("APPLICATION_ID not between", value1, value2, "applicationId");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeIsNull() {
			addCriterion("DL_SERVICE_CODE is null");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeIsNotNull() {
			addCriterion("DL_SERVICE_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeEqualTo(String value) {
			addCriterion("DL_SERVICE_CODE =", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeNotEqualTo(String value) {
			addCriterion("DL_SERVICE_CODE <>", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeGreaterThan(String value) {
			addCriterion("DL_SERVICE_CODE >", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeGreaterThanOrEqualTo(String value) {
			addCriterion("DL_SERVICE_CODE >=", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeLessThan(String value) {
			addCriterion("DL_SERVICE_CODE <", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeLessThanOrEqualTo(String value) {
			addCriterion("DL_SERVICE_CODE <=", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeLike(String value) {
			addCriterion("DL_SERVICE_CODE like", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeNotLike(String value) {
			addCriterion("DL_SERVICE_CODE not like", value, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeIn(List<String> values) {
			addCriterion("DL_SERVICE_CODE in", values, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeNotIn(List<String> values) {
			addCriterion("DL_SERVICE_CODE not in", values, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeBetween(String value1, String value2) {
			addCriterion("DL_SERVICE_CODE between", value1, value2, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlServiceCodeNotBetween(String value1, String value2) {
			addCriterion("DL_SERVICE_CODE not between", value1, value2, "dlServiceCode");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampIsNull() {
			addCriterion("DL_UPDATE_STAMP is null");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampIsNotNull() {
			addCriterion("DL_UPDATE_STAMP is not null");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampEqualTo(Short value) {
			addCriterion("DL_UPDATE_STAMP =", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampNotEqualTo(Short value) {
			addCriterion("DL_UPDATE_STAMP <>", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampGreaterThan(Short value) {
			addCriterion("DL_UPDATE_STAMP >", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampGreaterThanOrEqualTo(Short value) {
			addCriterion("DL_UPDATE_STAMP >=", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampLessThan(Short value) {
			addCriterion("DL_UPDATE_STAMP <", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampLessThanOrEqualTo(Short value) {
			addCriterion("DL_UPDATE_STAMP <=", value, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampIn(List<Short> values) {
			addCriterion("DL_UPDATE_STAMP in", values, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampNotIn(List<Short> values) {
			addCriterion("DL_UPDATE_STAMP not in", values, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampBetween(Short value1, Short value2) {
			addCriterion("DL_UPDATE_STAMP between", value1, value2, "dlUpdateStamp");
			return (Criteria) this;
		}

		public Criteria andDlUpdateStampNotBetween(Short value1, Short value2) {
			addCriterion("DL_UPDATE_STAMP not between", value1, value2, "dlUpdateStamp");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ABACUS.ABA_PD_NATN_INFO
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ABACUS.ABA_PD_NATN_INFO
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 20 14:06:41 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}