package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.TmSectRate;
import com.acube.pc.domain.TmSectRateExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TmSectRateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(TmSectRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(TmSectRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("inventoryItemId") Long inventoryItemId, @Param("timeBandCd") String timeBandCd, @Param("tmZoneId") String tmZoneId, @Param("dowCd") String dowCd,
			@Param("strtTm") String strtTm, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(TmSectRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(TmSectRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<TmSectRate> selectByExampleWithRowbounds(TmSectRateExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<TmSectRate> selectByExample(TmSectRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	TmSectRate selectByPrimaryKey(@Param("inventoryItemId") Long inventoryItemId, @Param("timeBandCd") String timeBandCd, @Param("tmZoneId") String tmZoneId, @Param("dowCd") String dowCd,
			@Param("strtTm") String strtTm, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") TmSectRate record, @Param("example") TmSectRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") TmSectRate record, @Param("example") TmSectRateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(TmSectRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_TM_SECT_RATE
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(TmSectRate record);
}