package com.acube.pvs.mapper.mbg;

import com.acube.pvs.domain.PsCsMessage;
import com.acube.pvs.domain.PsCsMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PsCsMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int countByExample(PsCsMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByExample(PsCsMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByPrimaryKey(String pvReqSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insert(PsCsMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insertSelective(PsCsMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsCsMessage> selectByExampleWithRowbounds(PsCsMessageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsCsMessage> selectByExample(PsCsMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    PsCsMessage selectByPrimaryKey(String pvReqSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") PsCsMessage record, @Param("example") PsCsMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExample(@Param("record") PsCsMessage record, @Param("example") PsCsMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKeySelective(PsCsMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_CS_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKey(PsCsMessage record);
}