package com.acube.pvs.mapper.mbg;

import com.acube.pvs.domain.PsNeMessage;
import com.acube.pvs.domain.PsNeMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PsNeMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int countByExample(PsNeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByExample(PsNeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByPrimaryKey(@Param("pvReqSeqNo") String pvReqSeqNo, @Param("neSeqno") Long neSeqno, @Param("reqDt") String reqDt, @Param("srcFtrCd") String srcFtrCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insert(PsNeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insertSelective(PsNeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsNeMessage> selectByExampleWithRowbounds(PsNeMessageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsNeMessage> selectByExample(PsNeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    PsNeMessage selectByPrimaryKey(@Param("pvReqSeqNo") String pvReqSeqNo, @Param("neSeqno") Long neSeqno, @Param("reqDt") String reqDt, @Param("srcFtrCd") String srcFtrCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") PsNeMessage record, @Param("example") PsNeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExample(@Param("record") PsNeMessage record, @Param("example") PsNeMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKeySelective(PsNeMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MESSAGE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKey(PsNeMessage record);
}