package com.acube.pvs.mapper.mbg;

import com.acube.pvs.domain.PsSysResource;
import com.acube.pvs.domain.PsSysResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PsSysResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int countByExample(PsSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByExample(PsSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByPrimaryKey(@Param("hostname") String hostname, @Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insert(PsSysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insertSelective(PsSysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsSysResource> selectByExampleWithRowbounds(PsSysResourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsSysResource> selectByExample(PsSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    PsSysResource selectByPrimaryKey(@Param("hostname") String hostname, @Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") PsSysResource record, @Param("example") PsSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExample(@Param("record") PsSysResource record, @Param("example") PsSysResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKeySelective(PsSysResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_RESOURCE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKey(PsSysResource record);
}