package com.acube.pvs.mapper.mbg;

import com.acube.pvs.domain.PsSysCpuHist;
import com.acube.pvs.domain.PsSysCpuHistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PsSysCpuHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int countByExample(PsSysCpuHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByExample(PsSysCpuHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int deleteByPrimaryKey(@Param("datetime") String datetime, @Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insert(PsSysCpuHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int insertSelective(PsSysCpuHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsSysCpuHist> selectByExampleWithRowbounds(PsSysCpuHistExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    List<PsSysCpuHist> selectByExample(PsSysCpuHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    PsSysCpuHist selectByPrimaryKey(@Param("datetime") String datetime, @Param("name") String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExampleSelective(@Param("record") PsSysCpuHist record, @Param("example") PsSysCpuHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByExample(@Param("record") PsSysCpuHist record, @Param("example") PsSysCpuHistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKeySelective(PsSysCpuHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_SYS_CPU_HIST
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    int updateByPrimaryKey(PsSysCpuHist record);
}