package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.DscntPrtySetCd;
import com.acube.pc.domain.DscntPrtySetCdExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DscntPrtySetCdMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(DscntPrtySetCdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(DscntPrtySetCdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(String dscntPrtySetCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(DscntPrtySetCd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(DscntPrtySetCd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DscntPrtySetCd> selectByExampleWithRowbounds(DscntPrtySetCdExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<DscntPrtySetCd> selectByExample(DscntPrtySetCdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	DscntPrtySetCd selectByPrimaryKey(String dscntPrtySetCd);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") DscntPrtySetCd record, @Param("example") DscntPrtySetCdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") DscntPrtySetCd record, @Param("example") DscntPrtySetCdExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(DscntPrtySetCd record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_DSCNT_PRTY_SET_CD
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(DscntPrtySetCd record);
}