package com.acube.pvs.domain;

import java.util.ArrayList;
import java.util.List;

public class PsNeMsgViewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public PsNeMsgViewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReqDtIsNull() {
            addCriterion("REQ_DT is null");
            return (Criteria) this;
        }

        public Criteria andReqDtIsNotNull() {
            addCriterion("REQ_DT is not null");
            return (Criteria) this;
        }

        public Criteria andReqDtEqualTo(String value) {
            addCriterion("REQ_DT =", value, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtNotEqualTo(String value) {
            addCriterion("REQ_DT <>", value, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtGreaterThan(String value) {
            addCriterion("REQ_DT >", value, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtGreaterThanOrEqualTo(String value) {
            addCriterion("REQ_DT >=", value, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtLessThan(String value) {
            addCriterion("REQ_DT <", value, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtLessThanOrEqualTo(String value) {
            addCriterion("REQ_DT <=", value, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtLike(String value) {
            addCriterion("REQ_DT like", value, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtNotLike(String value) {
            addCriterion("REQ_DT not like", value, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtIn(List<String> values) {
            addCriterion("REQ_DT in", values, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtNotIn(List<String> values) {
            addCriterion("REQ_DT not in", values, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtBetween(String value1, String value2) {
            addCriterion("REQ_DT between", value1, value2, "reqDt");
            return (Criteria) this;
        }

        public Criteria andReqDtNotBetween(String value1, String value2) {
            addCriterion("REQ_DT not between", value1, value2, "reqDt");
            return (Criteria) this;
        }

        public Criteria andEventCdIsNull() {
            addCriterion("EVENT_CD is null");
            return (Criteria) this;
        }

        public Criteria andEventCdIsNotNull() {
            addCriterion("EVENT_CD is not null");
            return (Criteria) this;
        }

        public Criteria andEventCdEqualTo(String value) {
            addCriterion("EVENT_CD =", value, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdNotEqualTo(String value) {
            addCriterion("EVENT_CD <>", value, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdGreaterThan(String value) {
            addCriterion("EVENT_CD >", value, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdGreaterThanOrEqualTo(String value) {
            addCriterion("EVENT_CD >=", value, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdLessThan(String value) {
            addCriterion("EVENT_CD <", value, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdLessThanOrEqualTo(String value) {
            addCriterion("EVENT_CD <=", value, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdLike(String value) {
            addCriterion("EVENT_CD like", value, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdNotLike(String value) {
            addCriterion("EVENT_CD not like", value, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdIn(List<String> values) {
            addCriterion("EVENT_CD in", values, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdNotIn(List<String> values) {
            addCriterion("EVENT_CD not in", values, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdBetween(String value1, String value2) {
            addCriterion("EVENT_CD between", value1, value2, "eventCd");
            return (Criteria) this;
        }

        public Criteria andEventCdNotBetween(String value1, String value2) {
            addCriterion("EVENT_CD not between", value1, value2, "eventCd");
            return (Criteria) this;
        }

        public Criteria andTargetNeIsNull() {
            addCriterion("TARGET_NE is null");
            return (Criteria) this;
        }

        public Criteria andTargetNeIsNotNull() {
            addCriterion("TARGET_NE is not null");
            return (Criteria) this;
        }

        public Criteria andTargetNeEqualTo(String value) {
            addCriterion("TARGET_NE =", value, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeNotEqualTo(String value) {
            addCriterion("TARGET_NE <>", value, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeGreaterThan(String value) {
            addCriterion("TARGET_NE >", value, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeGreaterThanOrEqualTo(String value) {
            addCriterion("TARGET_NE >=", value, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeLessThan(String value) {
            addCriterion("TARGET_NE <", value, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeLessThanOrEqualTo(String value) {
            addCriterion("TARGET_NE <=", value, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeLike(String value) {
            addCriterion("TARGET_NE like", value, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeNotLike(String value) {
            addCriterion("TARGET_NE not like", value, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeIn(List<String> values) {
            addCriterion("TARGET_NE in", values, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeNotIn(List<String> values) {
            addCriterion("TARGET_NE not in", values, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeBetween(String value1, String value2) {
            addCriterion("TARGET_NE between", value1, value2, "targetNe");
            return (Criteria) this;
        }

        public Criteria andTargetNeNotBetween(String value1, String value2) {
            addCriterion("TARGET_NE not between", value1, value2, "targetNe");
            return (Criteria) this;
        }

        public Criteria andStatusCdIsNull() {
            addCriterion("STATUS_CD is null");
            return (Criteria) this;
        }

        public Criteria andStatusCdIsNotNull() {
            addCriterion("STATUS_CD is not null");
            return (Criteria) this;
        }

        public Criteria andStatusCdEqualTo(String value) {
            addCriterion("STATUS_CD =", value, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdNotEqualTo(String value) {
            addCriterion("STATUS_CD <>", value, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdGreaterThan(String value) {
            addCriterion("STATUS_CD >", value, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS_CD >=", value, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdLessThan(String value) {
            addCriterion("STATUS_CD <", value, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdLessThanOrEqualTo(String value) {
            addCriterion("STATUS_CD <=", value, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdLike(String value) {
            addCriterion("STATUS_CD like", value, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdNotLike(String value) {
            addCriterion("STATUS_CD not like", value, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdIn(List<String> values) {
            addCriterion("STATUS_CD in", values, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdNotIn(List<String> values) {
            addCriterion("STATUS_CD not in", values, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdBetween(String value1, String value2) {
            addCriterion("STATUS_CD between", value1, value2, "statusCd");
            return (Criteria) this;
        }

        public Criteria andStatusCdNotBetween(String value1, String value2) {
            addCriterion("STATUS_CD not between", value1, value2, "statusCd");
            return (Criteria) this;
        }

        public Criteria andMinCntIsNull() {
            addCriterion("MIN_CNT is null");
            return (Criteria) this;
        }

        public Criteria andMinCntIsNotNull() {
            addCriterion("MIN_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andMinCntEqualTo(Long value) {
            addCriterion("MIN_CNT =", value, "minCnt");
            return (Criteria) this;
        }

        public Criteria andMinCntNotEqualTo(Long value) {
            addCriterion("MIN_CNT <>", value, "minCnt");
            return (Criteria) this;
        }

        public Criteria andMinCntGreaterThan(Long value) {
            addCriterion("MIN_CNT >", value, "minCnt");
            return (Criteria) this;
        }

        public Criteria andMinCntGreaterThanOrEqualTo(Long value) {
            addCriterion("MIN_CNT >=", value, "minCnt");
            return (Criteria) this;
        }

        public Criteria andMinCntLessThan(Long value) {
            addCriterion("MIN_CNT <", value, "minCnt");
            return (Criteria) this;
        }

        public Criteria andMinCntLessThanOrEqualTo(Long value) {
            addCriterion("MIN_CNT <=", value, "minCnt");
            return (Criteria) this;
        }

        public Criteria andMinCntIn(List<Long> values) {
            addCriterion("MIN_CNT in", values, "minCnt");
            return (Criteria) this;
        }

        public Criteria andMinCntNotIn(List<Long> values) {
            addCriterion("MIN_CNT not in", values, "minCnt");
            return (Criteria) this;
        }

        public Criteria andMinCntBetween(Long value1, Long value2) {
            addCriterion("MIN_CNT between", value1, value2, "minCnt");
            return (Criteria) this;
        }

        public Criteria andMinCntNotBetween(Long value1, Long value2) {
            addCriterion("MIN_CNT not between", value1, value2, "minCnt");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNull() {
            addCriterion("CREATE_DT is null");
            return (Criteria) this;
        }

        public Criteria andCreateDtIsNotNull() {
            addCriterion("CREATE_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDtEqualTo(String value) {
            addCriterion("CREATE_DT =", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotEqualTo(String value) {
            addCriterion("CREATE_DT <>", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThan(String value) {
            addCriterion("CREATE_DT >", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_DT >=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThan(String value) {
            addCriterion("CREATE_DT <", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLessThanOrEqualTo(String value) {
            addCriterion("CREATE_DT <=", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtLike(String value) {
            addCriterion("CREATE_DT like", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotLike(String value) {
            addCriterion("CREATE_DT not like", value, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtIn(List<String> values) {
            addCriterion("CREATE_DT in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotIn(List<String> values) {
            addCriterion("CREATE_DT not in", values, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtBetween(String value1, String value2) {
            addCriterion("CREATE_DT between", value1, value2, "createDt");
            return (Criteria) this;
        }

        public Criteria andCreateDtNotBetween(String value1, String value2) {
            addCriterion("CREATE_DT not between", value1, value2, "createDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 01 10:41:35 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PMSADM.ABA_PS_NE_MSG_VIEW
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}