package com.acube.pvs.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PsProvMapExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public PsProvMapExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSrcNeIdIsNull() {
            addCriterion("SRC_NE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdIsNotNull() {
            addCriterion("SRC_NE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdEqualTo(String value) {
            addCriterion("SRC_NE_ID =", value, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdNotEqualTo(String value) {
            addCriterion("SRC_NE_ID <>", value, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdGreaterThan(String value) {
            addCriterion("SRC_NE_ID >", value, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdGreaterThanOrEqualTo(String value) {
            addCriterion("SRC_NE_ID >=", value, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdLessThan(String value) {
            addCriterion("SRC_NE_ID <", value, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdLessThanOrEqualTo(String value) {
            addCriterion("SRC_NE_ID <=", value, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdLike(String value) {
            addCriterion("SRC_NE_ID like", value, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdNotLike(String value) {
            addCriterion("SRC_NE_ID not like", value, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdIn(List<String> values) {
            addCriterion("SRC_NE_ID in", values, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdNotIn(List<String> values) {
            addCriterion("SRC_NE_ID not in", values, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdBetween(String value1, String value2) {
            addCriterion("SRC_NE_ID between", value1, value2, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcNeIdNotBetween(String value1, String value2) {
            addCriterion("SRC_NE_ID not between", value1, value2, "srcNeId");
            return (Criteria) this;
        }

        public Criteria andSrcCmdIsNull() {
            addCriterion("SRC_CMD is null");
            return (Criteria) this;
        }

        public Criteria andSrcCmdIsNotNull() {
            addCriterion("SRC_CMD is not null");
            return (Criteria) this;
        }

        public Criteria andSrcCmdEqualTo(String value) {
            addCriterion("SRC_CMD =", value, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdNotEqualTo(String value) {
            addCriterion("SRC_CMD <>", value, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdGreaterThan(String value) {
            addCriterion("SRC_CMD >", value, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdGreaterThanOrEqualTo(String value) {
            addCriterion("SRC_CMD >=", value, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdLessThan(String value) {
            addCriterion("SRC_CMD <", value, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdLessThanOrEqualTo(String value) {
            addCriterion("SRC_CMD <=", value, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdLike(String value) {
            addCriterion("SRC_CMD like", value, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdNotLike(String value) {
            addCriterion("SRC_CMD not like", value, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdIn(List<String> values) {
            addCriterion("SRC_CMD in", values, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdNotIn(List<String> values) {
            addCriterion("SRC_CMD not in", values, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdBetween(String value1, String value2) {
            addCriterion("SRC_CMD between", value1, value2, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcCmdNotBetween(String value1, String value2) {
            addCriterion("SRC_CMD not between", value1, value2, "srcCmd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdIsNull() {
            addCriterion("SRC_FTR_CD is null");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdIsNotNull() {
            addCriterion("SRC_FTR_CD is not null");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdEqualTo(String value) {
            addCriterion("SRC_FTR_CD =", value, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdNotEqualTo(String value) {
            addCriterion("SRC_FTR_CD <>", value, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdGreaterThan(String value) {
            addCriterion("SRC_FTR_CD >", value, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdGreaterThanOrEqualTo(String value) {
            addCriterion("SRC_FTR_CD >=", value, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdLessThan(String value) {
            addCriterion("SRC_FTR_CD <", value, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdLessThanOrEqualTo(String value) {
            addCriterion("SRC_FTR_CD <=", value, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdLike(String value) {
            addCriterion("SRC_FTR_CD like", value, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdNotLike(String value) {
            addCriterion("SRC_FTR_CD not like", value, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdIn(List<String> values) {
            addCriterion("SRC_FTR_CD in", values, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdNotIn(List<String> values) {
            addCriterion("SRC_FTR_CD not in", values, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdBetween(String value1, String value2) {
            addCriterion("SRC_FTR_CD between", value1, value2, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andSrcFtrCdNotBetween(String value1, String value2) {
            addCriterion("SRC_FTR_CD not between", value1, value2, "srcFtrCd");
            return (Criteria) this;
        }

        public Criteria andProvOrderIsNull() {
            addCriterion("PROV_ORDER is null");
            return (Criteria) this;
        }

        public Criteria andProvOrderIsNotNull() {
            addCriterion("PROV_ORDER is not null");
            return (Criteria) this;
        }

        public Criteria andProvOrderEqualTo(Short value) {
            addCriterion("PROV_ORDER =", value, "provOrder");
            return (Criteria) this;
        }

        public Criteria andProvOrderNotEqualTo(Short value) {
            addCriterion("PROV_ORDER <>", value, "provOrder");
            return (Criteria) this;
        }

        public Criteria andProvOrderGreaterThan(Short value) {
            addCriterion("PROV_ORDER >", value, "provOrder");
            return (Criteria) this;
        }

        public Criteria andProvOrderGreaterThanOrEqualTo(Short value) {
            addCriterion("PROV_ORDER >=", value, "provOrder");
            return (Criteria) this;
        }

        public Criteria andProvOrderLessThan(Short value) {
            addCriterion("PROV_ORDER <", value, "provOrder");
            return (Criteria) this;
        }

        public Criteria andProvOrderLessThanOrEqualTo(Short value) {
            addCriterion("PROV_ORDER <=", value, "provOrder");
            return (Criteria) this;
        }

        public Criteria andProvOrderIn(List<Short> values) {
            addCriterion("PROV_ORDER in", values, "provOrder");
            return (Criteria) this;
        }

        public Criteria andProvOrderNotIn(List<Short> values) {
            addCriterion("PROV_ORDER not in", values, "provOrder");
            return (Criteria) this;
        }

        public Criteria andProvOrderBetween(Short value1, Short value2) {
            addCriterion("PROV_ORDER between", value1, value2, "provOrder");
            return (Criteria) this;
        }

        public Criteria andProvOrderNotBetween(Short value1, Short value2) {
            addCriterion("PROV_ORDER not between", value1, value2, "provOrder");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdIsNull() {
            addCriterion("TRGT_NE_ID is null");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdIsNotNull() {
            addCriterion("TRGT_NE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdEqualTo(String value) {
            addCriterion("TRGT_NE_ID =", value, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdNotEqualTo(String value) {
            addCriterion("TRGT_NE_ID <>", value, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdGreaterThan(String value) {
            addCriterion("TRGT_NE_ID >", value, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdGreaterThanOrEqualTo(String value) {
            addCriterion("TRGT_NE_ID >=", value, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdLessThan(String value) {
            addCriterion("TRGT_NE_ID <", value, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdLessThanOrEqualTo(String value) {
            addCriterion("TRGT_NE_ID <=", value, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdLike(String value) {
            addCriterion("TRGT_NE_ID like", value, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdNotLike(String value) {
            addCriterion("TRGT_NE_ID not like", value, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdIn(List<String> values) {
            addCriterion("TRGT_NE_ID in", values, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdNotIn(List<String> values) {
            addCriterion("TRGT_NE_ID not in", values, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdBetween(String value1, String value2) {
            addCriterion("TRGT_NE_ID between", value1, value2, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtNeIdNotBetween(String value1, String value2) {
            addCriterion("TRGT_NE_ID not between", value1, value2, "trgtNeId");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdIsNull() {
            addCriterion("TRGT_CMD is null");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdIsNotNull() {
            addCriterion("TRGT_CMD is not null");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdEqualTo(String value) {
            addCriterion("TRGT_CMD =", value, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdNotEqualTo(String value) {
            addCriterion("TRGT_CMD <>", value, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdGreaterThan(String value) {
            addCriterion("TRGT_CMD >", value, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdGreaterThanOrEqualTo(String value) {
            addCriterion("TRGT_CMD >=", value, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdLessThan(String value) {
            addCriterion("TRGT_CMD <", value, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdLessThanOrEqualTo(String value) {
            addCriterion("TRGT_CMD <=", value, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdLike(String value) {
            addCriterion("TRGT_CMD like", value, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdNotLike(String value) {
            addCriterion("TRGT_CMD not like", value, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdIn(List<String> values) {
            addCriterion("TRGT_CMD in", values, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdNotIn(List<String> values) {
            addCriterion("TRGT_CMD not in", values, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdBetween(String value1, String value2) {
            addCriterion("TRGT_CMD between", value1, value2, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtCmdNotBetween(String value1, String value2) {
            addCriterion("TRGT_CMD not between", value1, value2, "trgtCmd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdIsNull() {
            addCriterion("TRGT_FTR_CD is null");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdIsNotNull() {
            addCriterion("TRGT_FTR_CD is not null");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdEqualTo(String value) {
            addCriterion("TRGT_FTR_CD =", value, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdNotEqualTo(String value) {
            addCriterion("TRGT_FTR_CD <>", value, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdGreaterThan(String value) {
            addCriterion("TRGT_FTR_CD >", value, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdGreaterThanOrEqualTo(String value) {
            addCriterion("TRGT_FTR_CD >=", value, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdLessThan(String value) {
            addCriterion("TRGT_FTR_CD <", value, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdLessThanOrEqualTo(String value) {
            addCriterion("TRGT_FTR_CD <=", value, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdLike(String value) {
            addCriterion("TRGT_FTR_CD like", value, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdNotLike(String value) {
            addCriterion("TRGT_FTR_CD not like", value, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdIn(List<String> values) {
            addCriterion("TRGT_FTR_CD in", values, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdNotIn(List<String> values) {
            addCriterion("TRGT_FTR_CD not in", values, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdBetween(String value1, String value2) {
            addCriterion("TRGT_FTR_CD between", value1, value2, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andTrgtFtrCdNotBetween(String value1, String value2) {
            addCriterion("TRGT_FTR_CD not between", value1, value2, "trgtFtrCd");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagIsNull() {
            addCriterion("ERROR_CONTINUE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagIsNotNull() {
            addCriterion("ERROR_CONTINUE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagEqualTo(String value) {
            addCriterion("ERROR_CONTINUE_FLAG =", value, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagNotEqualTo(String value) {
            addCriterion("ERROR_CONTINUE_FLAG <>", value, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagGreaterThan(String value) {
            addCriterion("ERROR_CONTINUE_FLAG >", value, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ERROR_CONTINUE_FLAG >=", value, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagLessThan(String value) {
            addCriterion("ERROR_CONTINUE_FLAG <", value, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagLessThanOrEqualTo(String value) {
            addCriterion("ERROR_CONTINUE_FLAG <=", value, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagLike(String value) {
            addCriterion("ERROR_CONTINUE_FLAG like", value, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagNotLike(String value) {
            addCriterion("ERROR_CONTINUE_FLAG not like", value, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagIn(List<String> values) {
            addCriterion("ERROR_CONTINUE_FLAG in", values, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagNotIn(List<String> values) {
            addCriterion("ERROR_CONTINUE_FLAG not in", values, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagBetween(String value1, String value2) {
            addCriterion("ERROR_CONTINUE_FLAG between", value1, value2, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andErrorContinueFlagNotBetween(String value1, String value2) {
            addCriterion("ERROR_CONTINUE_FLAG not between", value1, value2, "errorContinueFlag");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchIsNull() {
            addCriterion("ROLLBACK_OR_BRANCH is null");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchIsNotNull() {
            addCriterion("ROLLBACK_OR_BRANCH is not null");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchEqualTo(String value) {
            addCriterion("ROLLBACK_OR_BRANCH =", value, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchNotEqualTo(String value) {
            addCriterion("ROLLBACK_OR_BRANCH <>", value, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchGreaterThan(String value) {
            addCriterion("ROLLBACK_OR_BRANCH >", value, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchGreaterThanOrEqualTo(String value) {
            addCriterion("ROLLBACK_OR_BRANCH >=", value, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchLessThan(String value) {
            addCriterion("ROLLBACK_OR_BRANCH <", value, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchLessThanOrEqualTo(String value) {
            addCriterion("ROLLBACK_OR_BRANCH <=", value, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchLike(String value) {
            addCriterion("ROLLBACK_OR_BRANCH like", value, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchNotLike(String value) {
            addCriterion("ROLLBACK_OR_BRANCH not like", value, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchIn(List<String> values) {
            addCriterion("ROLLBACK_OR_BRANCH in", values, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchNotIn(List<String> values) {
            addCriterion("ROLLBACK_OR_BRANCH not in", values, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchBetween(String value1, String value2) {
            addCriterion("ROLLBACK_OR_BRANCH between", value1, value2, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRollbackOrBranchNotBetween(String value1, String value2) {
            addCriterion("ROLLBACK_OR_BRANCH not between", value1, value2, "rollbackOrBranch");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdIsNull() {
            addCriterion("ROLEBACK_NE_CMD is null");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdIsNotNull() {
            addCriterion("ROLEBACK_NE_CMD is not null");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdEqualTo(String value) {
            addCriterion("ROLEBACK_NE_CMD =", value, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdNotEqualTo(String value) {
            addCriterion("ROLEBACK_NE_CMD <>", value, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdGreaterThan(String value) {
            addCriterion("ROLEBACK_NE_CMD >", value, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdGreaterThanOrEqualTo(String value) {
            addCriterion("ROLEBACK_NE_CMD >=", value, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdLessThan(String value) {
            addCriterion("ROLEBACK_NE_CMD <", value, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdLessThanOrEqualTo(String value) {
            addCriterion("ROLEBACK_NE_CMD <=", value, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdLike(String value) {
            addCriterion("ROLEBACK_NE_CMD like", value, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdNotLike(String value) {
            addCriterion("ROLEBACK_NE_CMD not like", value, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdIn(List<String> values) {
            addCriterion("ROLEBACK_NE_CMD in", values, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdNotIn(List<String> values) {
            addCriterion("ROLEBACK_NE_CMD not in", values, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdBetween(String value1, String value2) {
            addCriterion("ROLEBACK_NE_CMD between", value1, value2, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andRolebackNeCmdNotBetween(String value1, String value2) {
            addCriterion("ROLEBACK_NE_CMD not between", value1, value2, "rolebackNeCmd");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdIsNull() {
            addCriterion("EXCEPTION_FLOW_ID is null");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdIsNotNull() {
            addCriterion("EXCEPTION_FLOW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdEqualTo(String value) {
            addCriterion("EXCEPTION_FLOW_ID =", value, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdNotEqualTo(String value) {
            addCriterion("EXCEPTION_FLOW_ID <>", value, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdGreaterThan(String value) {
            addCriterion("EXCEPTION_FLOW_ID >", value, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdGreaterThanOrEqualTo(String value) {
            addCriterion("EXCEPTION_FLOW_ID >=", value, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdLessThan(String value) {
            addCriterion("EXCEPTION_FLOW_ID <", value, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdLessThanOrEqualTo(String value) {
            addCriterion("EXCEPTION_FLOW_ID <=", value, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdLike(String value) {
            addCriterion("EXCEPTION_FLOW_ID like", value, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdNotLike(String value) {
            addCriterion("EXCEPTION_FLOW_ID not like", value, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdIn(List<String> values) {
            addCriterion("EXCEPTION_FLOW_ID in", values, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdNotIn(List<String> values) {
            addCriterion("EXCEPTION_FLOW_ID not in", values, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdBetween(String value1, String value2) {
            addCriterion("EXCEPTION_FLOW_ID between", value1, value2, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andExceptionFlowIdNotBetween(String value1, String value2) {
            addCriterion("EXCEPTION_FLOW_ID not between", value1, value2, "exceptionFlowId");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateIsNull() {
            addCriterion("SYS_CREATION_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateIsNotNull() {
            addCriterion("SYS_CREATION_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateEqualTo(Date value) {
            addCriterion("SYS_CREATION_DATE =", value, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateNotEqualTo(Date value) {
            addCriterion("SYS_CREATION_DATE <>", value, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateGreaterThan(Date value) {
            addCriterion("SYS_CREATION_DATE >", value, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SYS_CREATION_DATE >=", value, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateLessThan(Date value) {
            addCriterion("SYS_CREATION_DATE <", value, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateLessThanOrEqualTo(Date value) {
            addCriterion("SYS_CREATION_DATE <=", value, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateIn(List<Date> values) {
            addCriterion("SYS_CREATION_DATE in", values, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateNotIn(List<Date> values) {
            addCriterion("SYS_CREATION_DATE not in", values, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateBetween(Date value1, Date value2) {
            addCriterion("SYS_CREATION_DATE between", value1, value2, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysCreationDateNotBetween(Date value1, Date value2) {
            addCriterion("SYS_CREATION_DATE not between", value1, value2, "sysCreationDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateIsNull() {
            addCriterion("SYS_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateIsNotNull() {
            addCriterion("SYS_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateEqualTo(Date value) {
            addCriterion("SYS_UPDATE_DATE =", value, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateNotEqualTo(Date value) {
            addCriterion("SYS_UPDATE_DATE <>", value, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateGreaterThan(Date value) {
            addCriterion("SYS_UPDATE_DATE >", value, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SYS_UPDATE_DATE >=", value, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateLessThan(Date value) {
            addCriterion("SYS_UPDATE_DATE <", value, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("SYS_UPDATE_DATE <=", value, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateIn(List<Date> values) {
            addCriterion("SYS_UPDATE_DATE in", values, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateNotIn(List<Date> values) {
            addCriterion("SYS_UPDATE_DATE not in", values, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateBetween(Date value1, Date value2) {
            addCriterion("SYS_UPDATE_DATE between", value1, value2, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andSysUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("SYS_UPDATE_DATE not between", value1, value2, "sysUpdateDate");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("OPERATOR_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("OPERATOR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(String value) {
            addCriterion("OPERATOR_ID =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(String value) {
            addCriterion("OPERATOR_ID <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(String value) {
            addCriterion("OPERATOR_ID >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("OPERATOR_ID >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(String value) {
            addCriterion("OPERATOR_ID <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(String value) {
            addCriterion("OPERATOR_ID <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLike(String value) {
            addCriterion("OPERATOR_ID like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotLike(String value) {
            addCriterion("OPERATOR_ID not like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<String> values) {
            addCriterion("OPERATOR_ID in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<String> values) {
            addCriterion("OPERATOR_ID not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(String value1, String value2) {
            addCriterion("OPERATOR_ID between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(String value1, String value2) {
            addCriterion("OPERATOR_ID not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdIsNull() {
            addCriterion("APPLICATION_ID is null");
            return (Criteria) this;
        }

        public Criteria andApplicationIdIsNotNull() {
            addCriterion("APPLICATION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andApplicationIdEqualTo(String value) {
            addCriterion("APPLICATION_ID =", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdNotEqualTo(String value) {
            addCriterion("APPLICATION_ID <>", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdGreaterThan(String value) {
            addCriterion("APPLICATION_ID >", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdGreaterThanOrEqualTo(String value) {
            addCriterion("APPLICATION_ID >=", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdLessThan(String value) {
            addCriterion("APPLICATION_ID <", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdLessThanOrEqualTo(String value) {
            addCriterion("APPLICATION_ID <=", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdLike(String value) {
            addCriterion("APPLICATION_ID like", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdNotLike(String value) {
            addCriterion("APPLICATION_ID not like", value, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdIn(List<String> values) {
            addCriterion("APPLICATION_ID in", values, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdNotIn(List<String> values) {
            addCriterion("APPLICATION_ID not in", values, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdBetween(String value1, String value2) {
            addCriterion("APPLICATION_ID between", value1, value2, "applicationId");
            return (Criteria) this;
        }

        public Criteria andApplicationIdNotBetween(String value1, String value2) {
            addCriterion("APPLICATION_ID not between", value1, value2, "applicationId");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeIsNull() {
            addCriterion("DL_SERVICE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeIsNotNull() {
            addCriterion("DL_SERVICE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeEqualTo(String value) {
            addCriterion("DL_SERVICE_CODE =", value, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeNotEqualTo(String value) {
            addCriterion("DL_SERVICE_CODE <>", value, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeGreaterThan(String value) {
            addCriterion("DL_SERVICE_CODE >", value, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeGreaterThanOrEqualTo(String value) {
            addCriterion("DL_SERVICE_CODE >=", value, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeLessThan(String value) {
            addCriterion("DL_SERVICE_CODE <", value, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeLessThanOrEqualTo(String value) {
            addCriterion("DL_SERVICE_CODE <=", value, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeLike(String value) {
            addCriterion("DL_SERVICE_CODE like", value, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeNotLike(String value) {
            addCriterion("DL_SERVICE_CODE not like", value, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeIn(List<String> values) {
            addCriterion("DL_SERVICE_CODE in", values, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeNotIn(List<String> values) {
            addCriterion("DL_SERVICE_CODE not in", values, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeBetween(String value1, String value2) {
            addCriterion("DL_SERVICE_CODE between", value1, value2, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlServiceCodeNotBetween(String value1, String value2) {
            addCriterion("DL_SERVICE_CODE not between", value1, value2, "dlServiceCode");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampIsNull() {
            addCriterion("DL_UPDATE_STAMP is null");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampIsNotNull() {
            addCriterion("DL_UPDATE_STAMP is not null");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampEqualTo(Short value) {
            addCriterion("DL_UPDATE_STAMP =", value, "dlUpdateStamp");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampNotEqualTo(Short value) {
            addCriterion("DL_UPDATE_STAMP <>", value, "dlUpdateStamp");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampGreaterThan(Short value) {
            addCriterion("DL_UPDATE_STAMP >", value, "dlUpdateStamp");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampGreaterThanOrEqualTo(Short value) {
            addCriterion("DL_UPDATE_STAMP >=", value, "dlUpdateStamp");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampLessThan(Short value) {
            addCriterion("DL_UPDATE_STAMP <", value, "dlUpdateStamp");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampLessThanOrEqualTo(Short value) {
            addCriterion("DL_UPDATE_STAMP <=", value, "dlUpdateStamp");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampIn(List<Short> values) {
            addCriterion("DL_UPDATE_STAMP in", values, "dlUpdateStamp");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampNotIn(List<Short> values) {
            addCriterion("DL_UPDATE_STAMP not in", values, "dlUpdateStamp");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampBetween(Short value1, Short value2) {
            addCriterion("DL_UPDATE_STAMP between", value1, value2, "dlUpdateStamp");
            return (Criteria) this;
        }

        public Criteria andDlUpdateStampNotBetween(Short value1, Short value2) {
            addCriterion("DL_UPDATE_STAMP not between", value1, value2, "dlUpdateStamp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 01 10:41:35 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PMSADM.ABA_PS_PROV_MAP
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}