package com.acube.pvs.domain;

import java.math.BigDecimal;

public class PsSysDiskHist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMSADM.ABA_PS_SYS_DISK_HIST.DATETIME
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    private String datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMSADM.ABA_PS_SYS_DISK_HIST.NAME
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMSADM.ABA_PS_SYS_DISK_HIST.TOT
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    private Long tot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMSADM.ABA_PS_SYS_DISK_HIST.USE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    private Long use;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMSADM.ABA_PS_SYS_DISK_HIST.UNUSE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    private Long unuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMSADM.ABA_PS_SYS_DISK_HIST.RATIO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    private BigDecimal ratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PMSADM.ABA_PS_SYS_DISK_HIST.HOSTNAME
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    private String hostname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.DATETIME
     *
     * @return the value of PMSADM.ABA_PS_SYS_DISK_HIST.DATETIME
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.DATETIME
     *
     * @param datetime the value for PMSADM.ABA_PS_SYS_DISK_HIST.DATETIME
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setDatetime(String datetime) {
        this.datetime = datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.NAME
     *
     * @return the value of PMSADM.ABA_PS_SYS_DISK_HIST.NAME
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.NAME
     *
     * @param name the value for PMSADM.ABA_PS_SYS_DISK_HIST.NAME
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.TOT
     *
     * @return the value of PMSADM.ABA_PS_SYS_DISK_HIST.TOT
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public Long getTot() {
        return tot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.TOT
     *
     * @param tot the value for PMSADM.ABA_PS_SYS_DISK_HIST.TOT
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setTot(Long tot) {
        this.tot = tot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.USE
     *
     * @return the value of PMSADM.ABA_PS_SYS_DISK_HIST.USE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public Long getUse() {
        return use;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.USE
     *
     * @param use the value for PMSADM.ABA_PS_SYS_DISK_HIST.USE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setUse(Long use) {
        this.use = use;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.UNUSE
     *
     * @return the value of PMSADM.ABA_PS_SYS_DISK_HIST.UNUSE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public Long getUnuse() {
        return unuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.UNUSE
     *
     * @param unuse the value for PMSADM.ABA_PS_SYS_DISK_HIST.UNUSE
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setUnuse(Long unuse) {
        this.unuse = unuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.RATIO
     *
     * @return the value of PMSADM.ABA_PS_SYS_DISK_HIST.RATIO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public BigDecimal getRatio() {
        return ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.RATIO
     *
     * @param ratio the value for PMSADM.ABA_PS_SYS_DISK_HIST.RATIO
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setRatio(BigDecimal ratio) {
        this.ratio = ratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.HOSTNAME
     *
     * @return the value of PMSADM.ABA_PS_SYS_DISK_HIST.HOSTNAME
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public String getHostname() {
        return hostname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PMSADM.ABA_PS_SYS_DISK_HIST.HOSTNAME
     *
     * @param hostname the value for PMSADM.ABA_PS_SYS_DISK_HIST.HOSTNAME
     *
     * @mbggenerated Mon Dec 01 10:41:35 KST 2014
     */
    public void setHostname(String hostname) {
        this.hostname = hostname;
    }
}