package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.ContsCategory;
import com.acube.pc.domain.ContsCategoryExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ContsCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(ContsCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(ContsCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(String catgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(ContsCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(ContsCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ContsCategory> selectByExampleWithRowbounds(ContsCategoryExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<ContsCategory> selectByExample(ContsCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	ContsCategory selectByPrimaryKey(String catgId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") ContsCategory record, @Param("example") ContsCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") ContsCategory record, @Param("example") ContsCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(ContsCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_CONTS_CATEGORY
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(ContsCategory record);
}