package com.acube.common.mapper.mbg;

import com.acube.common.domain.mbg.RvDlrMstr;
import com.acube.common.domain.mbg.RvDlrMstrExample;
import com.acube.common.domain.mbg.RvDlrMstrKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RvDlrMstrMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int countByExample(RvDlrMstrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int deleteByExample(RvDlrMstrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int deleteByPrimaryKey(RvDlrMstrKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int insert(RvDlrMstr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int insertSelective(RvDlrMstr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	List<RvDlrMstr> selectByExampleWithRowbounds(RvDlrMstrExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	List<RvDlrMstr> selectByExample(RvDlrMstrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	RvDlrMstr selectByPrimaryKey(RvDlrMstrKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByExampleSelective(@Param("record") RvDlrMstr record, @Param("example") RvDlrMstrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByExample(@Param("record") RvDlrMstr record, @Param("example") RvDlrMstrExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByPrimaryKeySelective(RvDlrMstr record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_RV_DLR_MSTR
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByPrimaryKey(RvDlrMstr record);
}