package com.acube.common.mapper.mbg;

import com.acube.common.domain.mbg.SeGroup;
import com.acube.common.domain.mbg.SeGroupExample;
import com.acube.common.domain.mbg.SeGroupKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SeGroupMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int countByExample(SeGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int deleteByExample(SeGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int deleteByPrimaryKey(SeGroupKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int insert(SeGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int insertSelective(SeGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	List<SeGroup> selectByExampleWithRowbounds(SeGroupExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	List<SeGroup> selectByExample(SeGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	SeGroup selectByPrimaryKey(SeGroupKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByExampleSelective(@Param("record") SeGroup record, @Param("example") SeGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByExample(@Param("record") SeGroup record, @Param("example") SeGroupExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByPrimaryKeySelective(SeGroup record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_GROUP
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByPrimaryKey(SeGroup record);
}