package com.acube.common.mapper.mbg;

import com.acube.common.domain.mbg.SeSecurityProfileInfo;
import com.acube.common.domain.mbg.SeSecurityProfileInfoExample;
import com.acube.common.domain.mbg.SeSecurityProfileInfoKey;
import com.acube.common.domain.searchFilter.SearchFilter;
import com.acube.common.pagination.Pagination;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SeSecurityProfileInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int countByExample(SeSecurityProfileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int deleteByExample(SeSecurityProfileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int deleteByPrimaryKey(SeSecurityProfileInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int insert(SeSecurityProfileInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int insertSelective(SeSecurityProfileInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	List<SeSecurityProfileInfo> selectByExampleWithRowbounds(SeSecurityProfileInfoExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	List<SeSecurityProfileInfo> selectByExample(SeSecurityProfileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	SeSecurityProfileInfo selectByPrimaryKey(SeSecurityProfileInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByExampleSelective(@Param("record") SeSecurityProfileInfo record, @Param("example") SeSecurityProfileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByExample(@Param("record") SeSecurityProfileInfo record, @Param("example") SeSecurityProfileInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByPrimaryKeySelective(SeSecurityProfileInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_SE_SECURITY_PROFILE_INFO
	 * @mbggenerated  Mon Dec 29 18:19:29 KST 2014
	 */
	int updateByPrimaryKey(SeSecurityProfileInfo record);

	/**
	 * <pre>
	 * 1. abstract : 
	 * 2. procedure : 
	 * </pre>
	 * @Method Name : getProfileList
	 * @date : 2014. 12. 29.
	 * @author : ChoiKangYou
	 * @history : 
	 *	-----------------------------------------------------------------------
	 *	change date	developer		       change log  
	 *	----------- ------------------- ---------------------------------------
	 *	2014. 12. 29.		ChoiKangYou			        init. 
	 *	-----------------------------------------------------------------------
	 * 
	 * @param searchFilter
	 * @param pagination
	 * @return
	 */ 	
	List<SeSecurityProfileInfo> getProfileList(SearchFilter searchFilter, Pagination pagination);
}