package com.acube.pc.mapper.mbg;

import com.acube.pc.domain.FtrByRvnu;
import com.acube.pc.domain.FtrByRvnuExample;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FtrByRvnuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int countByExample(FtrByRvnuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByExample(FtrByRvnuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int deleteByPrimaryKey(@Param("ftrCd") String ftrCd, @Param("rvnuDvCd") String rvnuDvCd, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insert(FtrByRvnu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int insertSelective(FtrByRvnu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<FtrByRvnu> selectByExampleWithRowbounds(FtrByRvnuExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	List<FtrByRvnu> selectByExample(FtrByRvnuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	FtrByRvnu selectByPrimaryKey(@Param("ftrCd") String ftrCd, @Param("rvnuDvCd") String rvnuDvCd, @Param("valdStrtDt") Date valdStrtDt);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExampleSelective(@Param("record") FtrByRvnu record, @Param("example") FtrByRvnuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByExample(@Param("record") FtrByRvnu record, @Param("example") FtrByRvnuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKeySelective(FtrByRvnu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ABACUS.ABA_PD_FTR_BY_RVNU
	 * @mbggenerated  Thu Nov 27 11:27:55 KST 2014
	 */
	int updateByPrimaryKey(FtrByRvnu record);
}